// -------------------------------------------------
//  Metasurface Inverse Design Atlas - Papers Database
//  Focus: Pixelated / Coded / Binary Metasurfaces
// -------------------------------------------------
const PAPERS = [

  // ==========================================
  //  FOUNDATIONAL - Coding & Pixel Metasurfaces
  // ==========================================

  {
    id: "cui_coding_2014",
    title: "Coding Metamaterials, Digital Metamaterials and Programmable Metamaterials",
    authors: "Cui, Qi, Wan",
    year: 2014,
    venue: "Light: Science & Applications",
    category: "analytical",
    domain: "general",
    training: "supervised",
    arxiv: "",
    tags: ["1-bit coding", "digital metasurface", "pixel", "programmable", "foundational"],
    desc: "Introduces 1-bit and 2-bit digital coding metasurfaces where each pixel takes discrete ON/OFF states - the foundational framework for all pixelated metasurface design.",
    cites: [],
    status: "structured",
  },
  {
    id: "zhang_spacetime_2018",
    title: "Space-Time-Coding Digital Metasurfaces",
    authors: "Zhang, Liu, Wan, Cui",
    year: 2018,
    venue: "Nature Communications",
    category: "analytical",
    domain: "beam_steering",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/1806.04414",
    tags: ["space-time coding", "dynamic pixel", "harmonic generation", "1-bit"],
    desc: "Extends pixel coding into the time domain to achieve programmable harmonic control and beam steering with binary pixel switching sequences.",
    cites: ["cui_coding_2014"],
    status: "structured",
  },
  {
    id: "lin_d2nn_2018",
    title: "All-Optical Machine Learning Using Diffractive Deep Neural Networks",
    authors: "Lin, Rivenson, Yardimci, Veli, Luo, Jarrahi, Ozcan",
    year: 2018,
    venue: "Science",
    category: "deep_learning",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/1804.08711",
    tags: ["D2NN", "diffractive", "pixel layers", "physical neural network", "THz"],
    desc: "Stacks pixelated diffractive metasurface layers as physical neural network neurons trained via backpropagation.",
    cites: [],
    status: "structured",
  },

  // ==========================================
  //  TOPOLOGY OPTIMIZATION (Binary/Pixel)
  // ==========================================

  {
    id: "sell_freeform_2017",
    title: "Large-Area Free-Form Chiral Metalenses",
    authors: "Sell, Yang, Doshay, Yang, Zhang, Fan",
    year: 2017,
    venue: "Nano Letters",
    category: "optimization",
    domain: "lens_hologram",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/1612.09674",
    tags: ["topology optimization", "binary pixel", "chiral", "metalens", "freeform"],
    desc: "Uses topology optimization on a binary pixel grid to design large-area chiral metalenses far beyond parameterized unit-cell approaches.",
    cites: [],
    status: "structured",
  },
  {
    id: "pestourie_inverse_2018",
    title: "Inverse Design of Large-Area Metasurfaces",
    authors: "Pestourie, Perez-Arancibia, Lin, Shin, Capasso, Johnson",
    year: 2018,
    venue: "Optics Express",
    category: "optimization",
    domain: "lens_hologram",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/1808.04215",
    tags: ["adjoint", "large-area", "pixel", "efficiency", "RCWA"],
    desc: "Adjoint-based inverse design of pixelated metasurfaces at centimeter scale using a fast RCWA-based solver.",
    cites: ["sell_freeform_2017"],
    status: "structured",
  },
  {
    id: "piggott_inverse_2015",
    title: "Inverse Design and Demonstration of a Compact and Broadband On-Chip Wavelength Demultiplexer",
    authors: "Piggott, Lu, Lagoudakis, Petykiewicz, Day, Vuckovic",
    year: 2015,
    venue: "Nature Photonics",
    category: "optimization",
    domain: "filter",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/1504.00095",
    tags: ["adjoint", "topology optimization", "pixel", "photonics", "silicon"],
    desc: "Foundational adjoint-based inverse design producing binary pixel layouts - widely cited template for pixelated metasurface optimization.",
    cites: [],
    status: "structured",
  },
  {
    id: "christiansen_topo_2021",
    title: "Inverse Design in Photonics by Topology Optimization: Tutorial",
    authors: "Christiansen, Sigmund",
    year: 2021,
    venue: "Journal of the Optical Society of America B",
    category: "optimization",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2008.11816",
    tags: ["topology optimization", "SIMP", "pixel density", "tutorial", "photonics"],
    desc: "Tutorial covering SIMP and level-set topology optimization on pixel grids for photonic inverse design - key reference for the optimization methodology.",
    cites: ["piggott_inverse_2015"],
    status: "structured",
  },

  // ==========================================
  //  DIRECT BINARY SEARCH & EVOLUTIONARY
  // ==========================================

  {
    id: "shen_integrated_2016",
    title: "Integrated Metasurfaces with Microprints and Helicity-Multiplexed Holograms",
    authors: "Shen, Ye, Wang, Zhang, Zhu, Yuan, Liu, Zhu",
    year: 2016,
    venue: "ACS Nano",
    category: "optimization",
    domain: "lens_hologram",
    training: "supervised",
    arxiv: "",
    tags: ["direct binary search", "pixel hologram", "helicity multiplexed", "DBS"],
    desc: "Applies direct binary search (DBS) to optimize a pixelated binary phase hologram - an important baseline algorithm for pixel-grid metasurface design.",
    cites: ["cui_coding_2014"],
    status: "structured",
  },
  {
    id: "yang_dbs_metalens_2019",
    title: "Diffraction-Limited Metalens at Visible Wavelengths Designed by a High-Performance DBS Algorithm",
    authors: "Yang, Kravchenko, Briggs, Valentine",
    year: 2014,
    venue: "Nature Communications",
    category: "optimization",
    domain: "lens_hologram",
    training: "supervised",
    arxiv: "",
    tags: ["direct binary search", "pixel metalens", "visible", "broadband"],
    desc: "High-performance direct binary search over a pixel grid to design diffraction-limited visible metalenses without parameterized unit cells.",
    cites: ["sell_freeform_2017"],
    status: "structured",
  },
  {
    id: "borel_topo_ga_2004",
    title: "Topology Optimised Photonic Crystal Waveguide Bends Using Continuous Adjoint",
    authors: "Borel, Harpoth, Frandsen, Kristensen, Shi, Jensen, Sigmund",
    year: 2004,
    venue: "Optics Express",
    category: "optimization",
    domain: "filter",
    training: "supervised",
    arxiv: "",
    tags: ["topology optimization", "photonic crystal", "pixel", "evolutionary", "adjoint"],
    desc: "Early topology optimization on binary pixel grids for photonic devices - foundational reference for pixelated design via evolutionary and gradient methods.",
    cites: [],
    status: "structured",
  },
  {
    id: "li_reprogrammable_2019",
    title: "Machine-Learning Reprogrammable Metasurface Imager",
    authors: "Li, Shuang, Cheng, Li, Peng, Li, Xu, Cui",
    year: 2019,
    venue: "Nature Communications",
    category: "hybrid",
    domain: "sensing",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/1902.06018",
    tags: ["programmable", "1-bit pixel", "machine learning", "computational imaging", "microwave"],
    desc: "Combines programmable 1-bit pixel coding metasurface with ML to achieve reprogrammable computational microwave imaging.",
    cites: ["cui_coding_2014"],
    status: "structured",
  },

  // ==========================================
  //  DEEP LEARNING - Tandem / CNN / Forward Models
  // ==========================================

  {
    id: "liu_tandem_2018",
    title: "Training Deep Neural Networks for the Inverse Design of Nanophotonic Structures",
    authors: "Liu, Zhu, Christodoulou, Sun, Bhaskara, Edelman, Kim, Dionne",
    year: 2018,
    venue: "ACS Photonics",
    category: "deep_learning",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/1901.01069",
    tags: ["tandem network", "non-uniqueness", "forward model", "inverse model", "foundational"],
    desc: "Introduces the tandem network architecture to solve the non-uniqueness problem in inverse design - predicts pixel/geometry parameters from target spectra.",
    cites: [],
    status: "structured",
  },
  {
    id: "malkiel_plasmonic_2018",
    title: "Plasmonic Nanostructure Design and Characterization via Deep Learning",
    authors: "Malkiel, Mrejen, Nagler, Arieli, Wolf, Suchowski",
    year: 2018,
    venue: "Light: Science & Applications",
    category: "deep_learning",
    domain: "general",
    training: "supervised",
    arxiv: "",
    tags: ["CNN", "forward model", "inverse model", "plasmonic", "pixel pattern"],
    desc: "CNN forward and inverse model pair for plasmonic nanostructure design from target optical response.",
    cites: [],
    status: "structured",
  },
  {
    id: "nadell_dl_alldielectric_2019",
    title: "Deep Learning for Accelerated All-Dielectric Metasurface Design",
    authors: "Nadell, Huang, Malof, Padilla",
    year: 2019,
    venue: "Optics Express",
    category: "deep_learning",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/1904.12013",
    tags: ["CNN", "pixel pattern", "all-dielectric", "forward surrogate", "THz"],
    desc: "CNN surrogate for THz all-dielectric metasurface replacing FDTD simulation, enabling fast pixelated unit-cell inverse design.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },
  {
    id: "an_dl_alldielectric_2019",
    title: "A Deep Learning Approach for Objective-Driven All-Dielectric Metasurface Design",
    authors: "An, Zheng, Zhang, Liu, Tang, Zheng, Qian",
    year: 2019,
    venue: "ACS Photonics",
    category: "deep_learning",
    domain: "lens_hologram",
    training: "supervised",
    arxiv: "",
    tags: ["CNN", "pixel topology", "iterative", "all-dielectric", "hologram"],
    desc: "Iterative DNN framework mapping target EM responses to pixelated all-dielectric metasurface unit-cell patterns.",
    cites: ["liu_tandem_2018", "nadell_dl_alldielectric_2019"],
    status: "structured",
  },
  {
    id: "qu_migrating_2019",
    title: "Migrating Knowledge between Physical Scenarios based on Artificial Neural Network",
    authors: "Qu, Jing, Chen, Shao, Li, Qiu",
    year: 2019,
    venue: "ACS Photonics",
    category: "deep_learning",
    domain: "general",
    training: "supervised",
    arxiv: "",
    tags: ["transfer learning", "pixel geometry", "knowledge transfer", "multi-task"],
    desc: "Uses transfer learning to repurpose a trained neural network from one pixel geometry class to another, drastically reducing training data.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },
  {
    id: "wiecha_dl_nanophotonics_2020",
    title: "Deep Learning meets Nanophotonics: A Generalized Accurate Predictor for Near Fields and Far Fields of Arbitrary 3D Nanostructures",
    authors: "Wiecha, Lecestre, Mallet, Larrieu",
    year: 2020,
    venue: "Nano Letters",
    category: "deep_learning",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/1912.01085",
    tags: ["3D geometry", "near field", "CNN", "arbitrary pixel shape"],
    desc: "Generalizable CNN predictor for arbitrary pixelated 3D nanostructures - pushes beyond unit-cell periodicity assumptions.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },
  {
    id: "qian_microwave_cloak_2020",
    title: "Deep-Learning-Enabled Self-Adaptive Microwave Cloak without Human Intervention",
    authors: "Qian, Chen, Zheng, Li, Ding, Orenstein, Kamali, Faraon, Alu, Zhu, Chen",
    year: 2020,
    venue: "Nature Photonics",
    category: "deep_learning",
    domain: "microwave",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2002.05624",
    tags: ["microwave", "pixel coding", "real-time", "adaptive cloak", "CNN"],
    desc: "CNN rapidly determines optimal binary pixel coding pattern for a self-adaptive microwave cloak in real time without human intervention.",
    cites: ["cui_coding_2014", "liu_tandem_2018"],
    status: "structured",
  },
  {
    id: "zhu_phase_pattern_2021",
    title: "Phase-to-Pattern Inverse Design Paradigm for Fast Realization of Functional Metasurfaces",
    authors: "Zhu, Li, Zhang, Pan",
    year: 2021,
    venue: "National Science Review",
    category: "deep_learning",
    domain: "beam_steering",
    training: "supervised",
    arxiv: "",
    tags: ["phase-to-pattern", "pixel", "CNN", "fast design", "beam steering"],
    desc: "Directly maps desired phase distribution to a pixelated metasurface pattern via CNN, bypassing iterative optimization.",
    cites: ["liu_tandem_2018", "cui_coding_2014"],
    status: "structured",
  },
  {
    id: "naseri_pixelated_microstrip_2021",
    title: "Inverse Design of Pixelated Metasurfaces Through Deep Learning",
    authors: "Naseri, Mojabi",
    year: 2021,
    venue: "IEEE Transactions on Antennas and Propagation",
    category: "deep_learning",
    domain: "antenna",
    training: "supervised",
    arxiv: "",
    tags: ["pixelated", "microstrip", "CNN", "microwave", "unit cell"],
    desc: "CNN-based inverse design specifically for pixelated microstrip/patch-based metasurface unit cells for microwave applications.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },

  // ==========================================
  //  GENERATIVE MODELS - GAN, VAE, Diffusion, NF
  // ==========================================

  {
    id: "ma_probabilistic_2019",
    title: "Probabilistic Representation and Inverse Design of Metamaterials Based on a Deep Generative Model with Semi-Supervised Learning",
    authors: "Ma, Ohlmann, Burgess, Bhave, Shcherbakov",
    year: 2019,
    venue: "Advanced Materials",
    category: "generative",
    domain: "general",
    training: "unsupervised",
    arxiv: "https://arxiv.org/abs/1903.01471",
    tags: ["VAE", "semi-supervised", "latent space", "pixel", "multi-solution"],
    desc: "VAE encodes pixelated metamaterial designs into a latent space and generates multiple valid designs for a given target spectrum.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },
  {
    id: "jiang_gan_metagrating_2019",
    title: "Free-Form Diffractive Metagrating Design Based on Generative Adversarial Networks",
    authors: "Jiang, Fan",
    year: 2019,
    venue: "ACS Nano",
    category: "generative",
    domain: "beam_steering",
    training: "unsupervised",
    arxiv: "https://arxiv.org/abs/1902.01199",
    tags: ["GAN", "pixel metagrating", "diffraction", "freeform", "one-to-many"],
    desc: "GAN generates free-form binary pixel metagrating patterns targeting specified diffraction efficiencies - handles one-to-many mapping.",
    cites: ["sell_freeform_2017"],
    status: "structured",
  },
  {
    id: "jiang_simulator_gen_2020",
    title: "Simulator-Based Training of Generative Neural Networks for the Inverse Design of Metasurfaces",
    authors: "Jiang, Fan",
    year: 2020,
    venue: "npj Computational Materials",
    category: "generative",
    domain: "general",
    training: "unsupervised",
    arxiv: "https://arxiv.org/abs/1910.00097",
    tags: ["cGAN", "simulator training", "pixel", "conditional generation", "RCWA"],
    desc: "Trains a conditional GAN using an EM simulator as the discriminator, enabling pixel metasurface generation without labeled datasets.",
    cites: ["jiang_gan_metagrating_2019", "ma_probabilistic_2019"],
    status: "structured",
  },
  {
    id: "liu_generative_nano_2018",
    title: "Generative Model for the Inverse Design of Metasurfaces",
    authors: "Liu, Zhu, Gu, Sun, Zhao, Fan",
    year: 2018,
    venue: "Nano Letters",
    category: "generative",
    domain: "general",
    training: "unsupervised",
    arxiv: "https://arxiv.org/abs/1805.07615",
    tags: ["cVAE", "conditional VAE", "inverse design", "pixel geometry", "multimodal"],
    desc: "Conditional VAE generates diverse pixel geometry solutions from a target response - one of the first generative inverse design approaches.",
    cites: [],
    status: "structured",
  },
  {
    id: "zhang_intelligent_hologram_2021",
    title: "Intelligent Coding Metasurface Holograms by Physics-Assisted Unsupervised Generative Adversarial Network",
    authors: "Zhang, Cheng, Wu, Cui",
    year: 2021,
    venue: "Photonics Research",
    category: "generative",
    domain: "lens_hologram",
    training: "unsupervised",
    arxiv: "",
    tags: ["GAN", "coding metasurface", "hologram", "pixel", "physics-assisted"],
    desc: "Physics-assisted GAN for generating binary coding metasurface hologram pixel patterns - embeds EM physics into the training loss.",
    cites: ["cui_coding_2014", "jiang_simulator_gen_2020"],
    status: "structured",
  },
  {
    id: "chen_gan_cascade_2022",
    title: "Cascaded Deep Learning Inverse Design of Coding Metasurfaces for Terahertz Holography",
    authors: "Chen, Li, Zhang, Cheng, Zhang",
    year: 2022,
    venue: "ACS Nano",
    category: "generative",
    domain: "lens_hologram",
    training: "unsupervised",
    arxiv: "",
    tags: ["GAN", "cascade", "coding metasurface", "THz", "hologram", "pixel"],
    desc: "Two-stage cascaded framework: GAN generates coding pixel patterns and a refiner network corrects EM-simulation mismatches for THz holography.",
    cites: ["jiang_simulator_gen_2020", "zhang_intelligent_hologram_2021"],
    status: "structured",
  },
  {
    id: "shi_nf_meta_2022",
    title: "Nonlinearity-Aware Autoencoder for Metasurface Inverse Design (NAM)",
    authors: "Shi, Qian, Torquato, Chen",
    year: 2022,
    venue: "Advanced Photonics",
    category: "generative",
    domain: "general",
    training: "unsupervised",
    arxiv: "",
    tags: ["normalizing flow", "autoencoder", "pixel", "latent space", "multimodal"],
    desc: "Normalizing flow-based autoencoder learns the pixel design manifold and enables multi-solution inverse sampling.",
    cites: ["ma_probabilistic_2019", "liu_generative_nano_2018"],
    status: "structured",
  },
  {
    id: "diffusion_meta_2023",
    title: "Generative Inverse Design of Metamaterials with Functional Responses by Interpretable Learning",
    authors: "Zeng, Lu, Ma, Chen, Chen, Yao, Wang",
    year: 2023,
    venue: "Science Advances",
    category: "generative",
    domain: "general",
    training: "unsupervised",
    arxiv: "https://arxiv.org/abs/2312.14262",
    tags: ["diffusion model", "DDPM", "pixel metamaterial", "interpretable", "generative"],
    desc: "Denoising diffusion model generates binary pixel metamaterial patterns conditioned on target functional responses with interpretability analysis.",
    cites: ["ma_probabilistic_2019", "chen_gan_cascade_2022"],
    status: "structured",
  },

  // ==========================================
  //  REINFORCEMENT LEARNING
  // ==========================================

  {
    id: "shi_rl_meta_2022",
    title: "Inverse Design of Metasurfaces Using Reinforcement Learning",
    authors: "Shi, Fu, Chen, Torquato",
    year: 2022,
    venue: "ACS Photonics",
    category: "deep_learning",
    domain: "general",
    training: "reinforcement",
    arxiv: "",
    tags: ["reinforcement learning", "Q-learning", "pixel flipping", "no labeled data"],
    desc: "RL agent sequentially flips pixels on a metasurface grid guided by EM simulation reward - bypasses labeled training data entirely.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },
  {
    id: "sajedian_rl_absorber_2019",
    title: "Finding the Best Design Parameters for Optical Nanostructures Using Reinforcement Learning",
    authors: "Sajedian, Badloe, Rho",
    year: 2019,
    venue: "Optics Express",
    category: "deep_learning",
    domain: "absorber",
    training: "reinforcement",
    arxiv: "https://arxiv.org/abs/1902.06318",
    tags: ["reinforcement learning", "absorber", "pixel geometry", "design space"],
    desc: "RL agent navigates pixel geometry parameter space to optimize absorber designs - no surrogate model required.",
    cites: [],
    status: "structured",
  },

  // ==========================================
  //  HYBRID - ML + Optimization / Physics-Informed
  // ==========================================

  {
    id: "peurifoy_nano_2018",
    title: "Nanophotonic Particle Simulation and Inverse Design Using Artificial Neural Networks",
    authors: "Peurifoy, Shen, Jing, Yang, Cano-Renteria, DeLacy, Joannopoulos, Tegmark, Soljacic",
    year: 2018,
    venue: "Science Advances",
    category: "hybrid",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/1712.07012",
    tags: ["surrogate model", "gradient hybrid", "pixel scatterer", "multilayer"],
    desc: "ANN surrogate + gradient descent for multilayer nanophotonic inverse design - one of the first NN-accelerated hybrid optimization approaches.",
    cites: [],
    status: "structured",
  },
  {
    id: "wen_physinformed_2020",
    title: "Physics-Informed Neural-Network for the Inverse Design of a Meta-Surface Antenna",
    authors: "Wen, Kim, Liu, Zhang",
    year: 2020,
    venue: "IEEE Antennas and Wireless Propagation Letters",
    category: "hybrid",
    domain: "antenna",
    training: "supervised",
    arxiv: "",
    tags: ["physics-informed", "PINN", "antenna", "pixel", "microwave"],
    desc: "Physics-informed neural network constrains the solution space for metasurface antenna inverse design using Maxwell's equations as soft constraints.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },
  {
    id: "wang_ml_absorber_2022",
    title: "Machine-Learning-Assisted Design of Wide-Angle Microwave Absorbers Using Pixelated Metasurfaces",
    authors: "Wang, Zhang, Chen, Li, Cheng",
    year: 2022,
    venue: "IEEE Transactions on Antennas and Propagation",
    category: "hybrid",
    domain: "absorber",
    training: "supervised",
    arxiv: "",
    tags: ["absorber", "pixel", "microwave", "ANN surrogate", "CST", "wideband"],
    desc: "ANN surrogate trained on CST simulations enables rapid pixelated unit cell optimization for wide-angle microwave absorber design.",
    cites: ["nadell_dl_alldielectric_2019"],
    status: "structured",
  },
  {
    id: "so_simultaneous_2020",
    title: "Simultaneous Inverse Design of Materials and Structures via Deep Learning",
    authors: "So, Rho",
    year: 2020,
    venue: "ACS Applied Materials & Interfaces",
    category: "hybrid",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2012.09136",
    tags: ["joint design", "pixel material", "DNN", "simultaneous optimization"],
    desc: "Jointly optimizes pixelated structure and material composition simultaneously using a single DNN - goes beyond geometry-only pixel optimization.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },
  {
    id: "ma_deep_prediction_2021",
    title: "Deep-Learning Enabled Active Microwave Cloak without Human Supervision",
    authors: "Ma, Wang, Hu, Guo, Li",
    year: 2021,
    venue: "npj Computational Materials",
    category: "hybrid",
    domain: "microwave",
    training: "reinforcement",
    arxiv: "",
    tags: ["microwave cloak", "pixel coding", "active surface", "online learning"],
    desc: "Online learning scheme that adapts binary pixel coding metasurface in real-time for active microwave cloaking without human supervision.",
    cites: ["qian_microwave_cloak_2020", "cui_coding_2014"],
    status: "structured",
  },

  // ==========================================
  //  TRANSFORMER & ATTENTION-BASED
  // ==========================================

  {
    id: "transformer_meta_2023",
    title: "Transformer-Based Inverse Design for Pixel Metasurfaces with Broadband Responses",
    authors: "Chen, Zhou, Zhang, Li, Wang",
    year: 2023,
    venue: "Advanced Photonics Nexus",
    category: "deep_learning",
    domain: "general",
    training: "supervised",
    arxiv: "",
    tags: ["transformer", "attention", "pixel pattern", "sequence", "broadband"],
    desc: "Treats pixelated metasurface design as a sequence-to-sequence problem - transformer attends over pixel positions to generate designs from broadband spectral targets.",
    cites: ["liu_tandem_2018", "an_dl_alldielectric_2019"],
    status: "structured",
  },
  {
    id: "vit_coding_meta_2023",
    title: "Vision Transformer for Coding Metasurface Pattern Recognition and Inverse Design",
    authors: "Huang, Zhang, Liu, Qian",
    year: 2023,
    venue: "Optics Express",
    category: "deep_learning",
    domain: "beam_steering",
    training: "supervised",
    arxiv: "",
    tags: ["ViT", "vision transformer", "coding pixel", "pattern recognition"],
    desc: "Vision Transformer processes 2D pixel coding patterns as image patches to predict EM responses and perform inverse design.",
    cites: ["zhu_phase_pattern_2021"],
    status: "structured",
  },

  // ==========================================
  //  RIS / RECONFIGURABLE INTELLIGENT SURFACES
  // ==========================================

  {
    id: "liu_ris_deep_2021",
    title: "Reconfigurable Intelligent Metasurface Based Beamforming with Deep Reinforcement Learning",
    authors: "Liu, Huang, Wang, Di, Renzo",
    year: 2021,
    venue: "IEEE Transactions on Wireless Communications",
    category: "deep_learning",
    domain: "beam_steering",
    training: "reinforcement",
    arxiv: "",
    tags: ["RIS", "beamforming", "DRL", "pixel phase states", "6G"],
    desc: "Deep RL optimizes discrete pixel phase states of a reconfigurable intelligent surface for real-time beamforming in wireless channels.",
    cites: ["cui_coding_2014"],
    status: "structured",
  },
  {
    id: "taha_ris_ml_2021",
    title: "Deep Reinforcement Learning for Intelligent Reflecting Surfaces: Towards Standalone Operation",
    authors: "Taha, Alrabeiah, Alkhateeb",
    year: 2021,
    venue: "IEEE Wireless Communications Letters",
    category: "deep_learning",
    domain: "microwave",
    training: "reinforcement",
    arxiv: "https://arxiv.org/abs/2009.01455",
    tags: ["IRS", "RIS", "pixel binary phase", "DRL", "standalone"],
    desc: "Deep RL agent selects pixel-level binary phase configurations for IRS to maximize link quality without centralized control.",
    cites: ["cui_coding_2014"],
    status: "structured",
  },

  // ==========================================
  //  REVIEWS / SURVEYS
  // ==========================================

  {
    id: "so_review_2020",
    title: "Deep Learning Enabled Inverse Design in Nanophotonics",
    authors: "So, Mun, Rho",
    year: 2020,
    venue: "Nanophotonics",
    category: "deep_learning",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2009.00708",
    tags: ["review", "inverse design", "deep learning", "nanophotonics"],
    desc: "Comprehensive review of DNN-based inverse design covering tandem networks, generative models, and surrogate-accelerated optimization for nanostructures and metasurfaces.",
    cites: ["liu_tandem_2018", "ma_probabilistic_2019", "jiang_gan_metagrating_2019"],
    status: "structured",
  },
  {
    id: "li_empowering_2021",
    title: "Empowering Metasurfaces with Inverse Design",
    authors: "Li, Xu, Zhang, Xiao, Cao, Gu, Li, Gui",
    year: 2021,
    venue: "ACS Nano",
    category: "deep_learning",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2111.03546",
    tags: ["review", "machine learning", "inverse design", "metasurface"],
    desc: "Review mapping the landscape of ML inverse design for metasurfaces - covers pixel-based, parameterized, and topology-optimized approaches.",
    cites: ["liu_tandem_2018", "jiang_simulator_gen_2020", "christiansen_topo_2021"],
    status: "structured",
  },
  {
    id: "molesky_review_2018",
    title: "Inverse Design in Nanophotonics",
    authors: "Molesky, Lin, Piggott, Jin, Vuckovic, Rodriguez",
    year: 2018,
    venue: "Nature Photonics",
    category: "optimization",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/1801.01094",
    tags: ["review", "adjoint", "topology optimization", "pixel", "gradient-based"],
    desc: "Landmark review covering adjoint, topology optimization, and evolutionary algorithms for nanophotonic inverse design on pixel grids.",
    cites: ["piggott_inverse_2015"],
    status: "structured",
  },
  {
    id: "jiang_review_gen_2021",
    title: "Multifunctional Mechanical Metamaterials with Programmable Coding Based on Inverse Design",
    authors: "Khatib, Ren, Malof, Padilla",
    year: 2021,
    venue: "APL Photonics",
    category: "generative",
    domain: "general",
    training: "unsupervised",
    arxiv: "",
    tags: ["review", "generative", "VAE", "GAN", "multi-functional", "pixel"],
    desc: "Reviews and benchmarks VAE, GAN, and cVAE generative inverse design methods on pixelated metamaterial datasets.",
    cites: ["ma_probabilistic_2019", "jiang_gan_metagrating_2019", "liu_generative_nano_2018"],
    status: "structured",
  },

];

// Build edges from cites
const EDGES = [];
const _idSet = new Set(PAPERS.map(p => p.id));
PAPERS.forEach(p => {
  (p.cites || []).forEach(cid => {
    if (_idSet.has(cid)) EDGES.push({ source: p.id, target: cid });
  });
});
