// Metasurface Inverse Design Atlas - papers.js
// Focus: Pixelated / Coded / Binary Metasurfaces
//        Emphasis on patch antenna, FSS, and filter applications
// -------------------------------------------------------------
const PAPERS = [

  // ===============================================
  //  FOUNDATIONAL - Coding / Digital Pixel Paradigm
  // ===============================================

  {
    id: "cui_coding_2014",
    title: "Coding Metamaterials, Digital Metamaterials and Programmable Metamaterials",
    authors: "Cui, Qi, Wan",
    year: 2014,
    venue: "Light: Science & Applications",
    category: "analytical",
    domain: "general",
    training: "supervised",
    arxiv: "",
    tags: ["1-bit coding","digital metasurface","pixel","programmable","foundational"],
    desc: "Introduces 1-bit and 2-bit digital coding metasurfaces where each pixel is ON/OFF - the foundational framework for all pixelated metasurface design.",
    cites: [],
    status: "structured",
  },
  {
    id: "munk_fss_2000",
    title: "Frequency Selective Surfaces: Theory and Design",
    authors: "Munk",
    year: 2000,
    venue: "Wiley-Interscience",
    category: "analytical",
    domain: "filter",
    training: "supervised",
    arxiv: "",
    tags: ["FSS","frequency selective surface","analytical","foundational","bandpass","bandstop"],
    desc: "The foundational analytical reference for frequency-selective surfaces - unit-cell resonance, polarisation, and angular stability theory underpinning all FSS optimisation work.",
    cites: [],
    status: "structured",
  },
  {
    id: "kennedy_pso_1995",
    title: "Particle Swarm Optimization",
    authors: "Kennedy, Eberhart",
    year: 1995,
    venue: "ICNN",
    category: "optimization",
    domain: "general",
    training: "supervised",
    arxiv: "",
    tags: ["PSO","swarm intelligence","foundational","continuous optimization"],
    desc: "Original PSO paper - the continuous-space swarm algorithm that all BPSO / binary-PSO metasurface variants extend.",
    cites: [],
    status: "structured",
  },
  {
    id: "kennedy_bpso_1997",
    title: "A Discrete Binary Version of the Particle Swarm Algorithm",
    authors: "Kennedy, Eberhart",
    year: 1997,
    venue: "IEEE ICSMC",
    category: "optimization",
    domain: "general",
    training: "supervised",
    arxiv: "",
    tags: ["BPSO","binary PSO","S-shaped transfer","discrete optimization","foundational"],
    desc: "Introduces Binary PSO (S-shaped sigmoid transfer function) - the direct predecessor of all V-shaped and modified BPSO methods used in pixelated metasurface design.",
    cites: ["kennedy_pso_1995"],
    status: "structured",
  },
  {
    id: "mirjalili_sv_2013",
    title: "S-shaped versus V-shaped Transfer Functions for Binary Particle Swarm Optimization",
    authors: "Mirjalili, Lewis",
    year: 2013,
    venue: "Swarm and Evolutionary Computation",
    category: "optimization",
    domain: "general",
    training: "supervised",
    arxiv: "",
    tags: ["BPSO","V-shaped transfer","S-shaped transfer","benchmark","flip-based"],
    desc: "Systematic comparison of S-shaped vs V-shaped transfer functions in BPSO - shows V-shaped flip-based variants outperform S-shaped; the benchmark reference for MVBPSO.",
    cites: ["kennedy_bpso_1997"],
    status: "structured",
  },
  {
    id: "deb_nsga2_2002",
    title: "A Fast and Elitist Multiobjective Genetic Algorithm: NSGA-II",
    authors: "Deb, Pratap, Agarwal, Meyarivan",
    year: 2002,
    venue: "IEEE Transactions on Evolutionary Computation",
    category: "optimization",
    domain: "general",
    training: "supervised",
    arxiv: "",
    tags: ["NSGA-II","multi-objective","Pareto","genetic algorithm","foundational"],
    desc: "NSGA-II - the standard multi-objective evolutionary algorithm used as the backbone optimizer in surrogate-assisted antenna and FSS design frameworks.",
    cites: [],
    status: "structured",
  },

  // ===============================================
  //  BINARY PSO / BPSO - Pixelated Metasurface
  // ===============================================

  {
    id: "kumar_mvbpso_2025",
    title: "Automated Design and Inverse Modelling of Metasurfaces using Modified V-shaped Binary Particle Swarm Optimization and Convolutional Neural Networks",
    authors: "Kumar, Krishna, Sarkar",
    year: 2025,
    venue: "IEEE Transactions on Antennas and Propagation",
    category: "hybrid",
    domain: "filter",
    training: "supervised",
    arxiv: "",
    tags: ["MVBPSO","BPSO","V-shaped transfer","CNN","pixelated","bandpass","bandstop","28GHz","79GHz","polarization-insensitive","CST","Python-CST API","swarm dataset","PIM-CNN","FR-4"],
    desc: "Fully automated MVBPSO + CNN pipeline for pixelated polarisation-insensitive bandpass/bandstop metasurface filters at 28 GHz and 79 GHz. Derives a modified V-shaped transfer function with exploration-exploitation ratio nearest to unity (1.037); swarm-assisted dataset generation cuts required training samples by 50-60% vs random sampling; CNN achieves sub-1% MSE with 3 MB model and 0.169 s inference.",
    cites: ["kennedy_bpso_1997","mirjalili_sv_2013","liu_tandem_2018","zhang_rl_pso_2022","munk_fss_2000"],
    status: "structured",
  },
  {
    id: "chandrakapure_pso_meta_2024",
    title: "Automated Design of Pixelated Metasurfaces using Particle Swarm Optimization for Diverse Applications",
    authors: "Chandrakapure, Kumar, Joshi, Lakhtakia, Sarkar",
    year: 2024,
    venue: "IEEE MAPCON",
    category: "optimization",
    domain: "filter",
    training: "supervised",
    arxiv: "",
    tags: ["PSO","pixelated","MATLAB-CST","automation","15GHz","bandpass","bandstop","microwave"],
    desc: "MATLAB-CST API-assisted continuous PSO for automated pixelated metasurface design across multiple functions - direct predecessor of the MVBPSO framework.",
    cites: ["kennedy_pso_1995","kumar_mvbpso_2025"],
    status: "structured",
  },
  {
    id: "shan_bpso_rcs_2022",
    title: "BPSO and Staggered Triangle Layout Optimization for Wideband RCS Reduction of Pixelate Checkerboard Metasurface",
    authors: "Shan, Jiang, Xing, Jiang",
    year: 2022,
    venue: "IEEE Transactions on Microwave Theory and Techniques",
    category: "optimization",
    domain: "beam_steering",
    training: "supervised",
    arxiv: "",
    tags: ["BPSO","checkerboard","RCS reduction","pixel","wideband","microwave"],
    desc: "Binary PSO applied to pixelated checkerboard metasurface layout optimisation for wideband radar cross-section reduction - key BPSO application in microwave domain.",
    cites: ["kennedy_bpso_1997","mirjalili_sv_2013"],
    status: "structured",
  },

  // ===============================================
  //  ANT COLONY OPTIMIZATION - FSS / 3D Structures
  // ===============================================

  {
    id: "zhu_molaco_tap_2017",
    title: "Design and Optimization of 3-D Frequency-Selective Surfaces Based on a Multiobjective Lazy Ant Colony Optimization Algorithm",
    authors: "Zhu, Werner P L, Werner D H",
    year: 2017,
    venue: "IEEE Transactions on Antennas and Propagation",
    category: "optimization",
    domain: "filter",
    training: "supervised",
    arxiv: "",
    tags: ["ACO","MOLACO","lazy ant","FSS","3D FSS","multi-objective","Pareto","angular stability","polarization independent","wire grid","combinatorial","PFEBI"],
    desc: "Introduces MOLACO (Multi-Objective Lazy Ant Colony Optimization) with adaptive colony masking and phantom termination segments. Applied to 3D wire-grid FSS unit cells achieving <1% frequency shift and -10 dB rejection up to 80° incidence for both TE and TM polarisations - outperforms planar and multilayer FSS designs.",
    cites: ["munk_fss_2000","deb_nsga2_2002"],
    status: "structured",
  },
  {
    id: "zhu_molaco_aps_2018",
    title: "Multi-Objective Lazy Ant Colony Optimization for Frequency Selective Surface Design",
    authors: "Zhu, Werner P L, Werner D H",
    year: 2018,
    venue: "IEEE APS",
    category: "optimization",
    domain: "filter",
    training: "supervised",
    arxiv: "",
    tags: ["ACO","MOLACO","FSS","3D","multi-objective","combinatorial","GA-driven","lazy ant"],
    desc: "Conference companion to the IEEE TAP MOLACO paper - presents the algorithm overview and 9x9x2 3D FSS result with 13% stop bandwidth and 12% pass bandwidth up to 75° incidence.",
    cites: ["zhu_molaco_tap_2017","munk_fss_2000"],
    status: "structured",
  },
  {
    id: "bossard_ga_fss_2005",
    title: "A Novel Design Methodology for Reconfigurable Frequency Selective Surfaces Using Genetic Algorithms",
    authors: "Bossard, Werner, Mayer, Drupp",
    year: 2005,
    venue: "IEEE Transactions on Antennas and Propagation",
    category: "optimization",
    domain: "filter",
    training: "supervised",
    arxiv: "",
    tags: ["genetic algorithm","FSS","reconfigurable","binary","unit cell","pixel"],
    desc: "GA-based inverse design of reconfigurable FSS - early benchmark for evolutionary optimization of binary pixel FSS patterns, widely cited in MOLACO and BPSO FSS papers.",
    cites: ["munk_fss_2000"],
    status: "structured",
  },
  {
    id: "genovesi_pso_fss_2006",
    title: "Particle Swarm Optimization for the Design of Frequency Selective Surfaces",
    authors: "Genovesi, Mittra, Monorchio, Manara",
    year: 2006,
    venue: "IEEE Antennas and Wireless Propagation Letters",
    category: "optimization",
    domain: "filter",
    training: "supervised",
    arxiv: "",
    tags: ["PSO","FSS","particle swarm","pixel","planar","design"],
    desc: "Applies PSO to FSS unit-cell geometry optimisation - key reference establishing PSO as a viable alternative to GA for pixelated FSS design.",
    cites: ["kennedy_pso_1995","munk_fss_2000"],
    status: "structured",
  },

  // ===============================================
  //  SURROGATE-ASSISTED / MULTI-OBJECTIVE - Antenna
  // ===============================================

  {
    id: "easum_motol_2018",
    title: "Efficient Multiobjective Antenna Optimization With Tolerance Analysis Through the Use of Surrogate Models",
    authors: "Easum, Nagar, Werner P L, Werner D H",
    year: 2018,
    venue: "IEEE Transactions on Antennas and Propagation",
    category: "hybrid",
    domain: "antenna",
    training: "supervised",
    arxiv: "",
    tags: ["surrogate model","Kriging","GPR","polynomial regression","NSGA-II","multi-objective","Pareto","tolerance analysis","Vivaldi antenna","monopole","CMA-ES","MOTOL","AIC"],
    desc: "Introduces MOTOL: black-box multi-objective surrogate framework combining polynomial/Kriging/GPR model selection with tolerance hypervolume metric. Applied to Vivaldi (6-var, 810 EM evals, 60 h) and capacitively loaded monopole (6-var, 1310 evals, 41 h) - shows clear performance-robustness Pareto tradeoffs with 4.6 billion surrogate evaluations replacing expensive EM simulation.",
    cites: ["deb_nsga2_2002"],
    status: "structured",
  },
  {
    id: "easum_patch_surrogate_2016",
    title: "Multi-objective Surrogate-Assisted Optimization Applied to Patch Antenna Design",
    authors: "Easum, Nagar, Werner D H",
    year: 2016,
    venue: "IEEE APS",
    category: "hybrid",
    domain: "antenna",
    training: "supervised",
    arxiv: "",
    tags: ["surrogate model","patch antenna","Kriging","GPR","polynomial","NSGA-II","Pareto","gain","front-to-back ratio","ground plane","HFSS"],
    desc: "Surrogate-assisted multi-objective optimisation of a rectangular patch antenna on finite ground plane - simultaneously maximises gain, front-to-back ratio, and minimises ground plane area. Surrogate with 25 initial samples converges to better Pareto fronts than NSGA-II with 300 function evaluations.",
    cites: ["deb_nsga2_2002","easum_motol_2018"],
    status: "structured",
  },
  {
    id: "koziel_surr_antenna_2014",
    title: "Efficient Multiobjective Simulation-Driven Antenna Design Using Co-Kriging",
    authors: "Koziel, Bekasiewicz, Couckuyt, Dhaene",
    year: 2014,
    venue: "IEEE Transactions on Antennas and Propagation",
    category: "hybrid",
    domain: "antenna",
    training: "supervised",
    arxiv: "",
    tags: ["co-Kriging","surrogate","antenna","multi-objective","simulation-driven"],
    desc: "Co-Kriging surrogate model for efficient multi-objective antenna design - key surrogate baseline referenced in MOTOL and patch antenna surrogate frameworks.",
    cites: [],
    status: "structured",
  },
  {
    id: "prado_svr_reflectarray_2019",
    title: "Wideband Shaped-Beam Reflectarray Design Using Support Vector Regression Analysis",
    authors: "Prado, Lopez-Fernandez, Arrebola, Pino, Goussetis",
    year: 2019,
    venue: "IEEE Antennas and Wireless Propagation Letters",
    category: "hybrid",
    domain: "antenna",
    training: "supervised",
    arxiv: "",
    tags: ["SVR","support vector regression","reflectarray","surrogate","wideband","shaped beam","pixel"],
    desc: "SVR surrogate maps pixel-level antenna geometry to far-field shaped-beam response, achieving >10x speedup versus full-wave EM simulation - cited in MVBPSO as FSS surrogate baseline.",
    cites: [],
    status: "structured",
  },

  // ===============================================
  //  DEEP LEARNING - CNN Forward/Inverse Models
  // ===============================================

  {
    id: "liu_tandem_2018",
    title: "Training Deep Neural Networks for the Inverse Design of Nanophotonic Structures",
    authors: "Liu, Zhu, Christodoulou, Sun et al.",
    year: 2018,
    venue: "ACS Photonics",
    category: "deep_learning",
    domain: "general",
    training: "supervised",
    arxiv: "https://doi.org/10.1021/acsphotonics.7b01377",
    tags: ["tandem network","non-uniqueness","forward model","inverse model","foundational"],
    desc: "Introduces tandem network to handle non-uniqueness in inverse design - predicts pixel/geometry parameters from target spectra. The foundational DNN inverse design paper for metasurfaces.",
    cites: [],
    status: "structured",
  },
  {
    id: "an_deep_opex_2020",
    title: "Deep Learning Modeling Approach for Metasurfaces with High Degrees of Freedom",
    authors: "An, Zheng, Shalaginov, Tang, Li et al.",
    year: 2020,
    venue: "Optics Express",
    category: "deep_learning",
    domain: "general",
    training: "supervised",
    arxiv: "https://doi.org/10.1364/OE.401960",
    tags: ["CNN","dual-input","meta-atom spectra","pixel","high-DOF","forward surrogate"],
    desc: "Dual-input CNN predicts complex meta-atom spectra with MSE ~3.5e-4 requiring ~100,000 simulated training samples - the large-dataset CNN baseline referenced in MVBPSO.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },
  {
    id: "nadell_dl_alldielectric_2019",
    title: "Deep Learning for Accelerated All-Dielectric Metasurface Design",
    authors: "Nadell, Huang, Malof, Padilla",
    year: 2019,
    venue: "Optics Express",
    category: "deep_learning",
    domain: "general",
    training: "supervised",
    arxiv: "https://doi.org/10.1364/OE.27.027523",
    tags: ["CNN","pixel pattern","all-dielectric","THz","forward surrogate","FDTD replacement"],
    desc: "CNN surrogate for THz all-dielectric metasurface replacing FDTD simulation - key benchmark for CNN-based pixelated unit-cell forward modelling.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },
  {
    id: "naseri_pixelated_tap_2021",
    title: "Inverse Design of Pixelated Metasurfaces Through Deep Learning",
    authors: "Naseri, Mojabi",
    year: 2021,
    venue: "IEEE Transactions on Antennas and Propagation",
    category: "deep_learning",
    domain: "antenna",
    training: "supervised",
    arxiv: "",
    tags: ["CNN","pixelated","microstrip","microwave","unit cell","inverse model","patch"],
    desc: "CNN-based inverse design specifically for pixelated microstrip/patch-based metasurface unit cells for microwave applications - the closest DNN reference to the patch antenna focus.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },
  {
    id: "qian_microwave_cloak_2020",
    title: "Deep-Learning-Enabled Self-Adaptive Microwave Cloak without Human Intervention",
    authors: "Qian, Chen, Zheng et al.",
    year: 2020,
    venue: "Nature Photonics",
    category: "deep_learning",
    domain: "microwave",
    training: "supervised",
    arxiv: "https://doi.org/10.1038/s41566-020-0604-2",
    tags: ["microwave","pixel coding","real-time","adaptive","CNN","binary pixel"],
    desc: "CNN determines optimal binary pixel coding pattern for self-adaptive microwave cloak in real-time - demonstrates CNN speed advantage over iterative optimization for pixelated microwave designs.",
    cites: ["cui_coding_2014","liu_tandem_2018"],
    status: "structured",
  },
  {
    id: "lv_sidm_2024",
    title: "A Spatial Inverse Design Method (SIDM) Based on Machine Learning for Frequency-Selective-Surface (FSS) Structures",
    authors: "Lv, Xiao, Hu, Liu",
    year: 2024,
    venue: "IEEE Transactions on Antennas and Propagation",
    category: "deep_learning",
    domain: "filter",
    training: "supervised",
    arxiv: "https://doi.org/10.1109/TAP.2024.3355227",
    tags: ["MLP-Mixer","FSS","pixel","spatial","inverse design","frequency selective"],
    desc: "MLP-Mixer maps target spectra directly to 30x30 pixel-based FSS layout - higher accuracy than GA; the SIDM baseline method referenced in MVBPSO.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },
  {
    id: "lu_dpd_nn_2024",
    title: "Multiphysics Inverse Design of Frequency-Selective Surface by Data-Physics-Driven Deep Neural Network",
    authors: "Lu, Liu, Zong, Wei",
    year: 2024,
    venue: "IEEE Transactions on Antennas and Propagation",
    category: "hybrid",
    domain: "filter",
    training: "supervised",
    arxiv: "https://doi.org/10.1109/TAP.2024.3456902",
    tags: ["DPD-NN","PINN","physics-informed","FSS","inverse design","thermal","multiphysics"],
    desc: "Data-Physics-Driven NN combines inverse, physics-based, and forward models for FSS meeting both EM and thermal requirements - multiphysics pixelated FSS inverse design baseline.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },
  {
    id: "zhu_arftdl_2022",
    title: "Adversarial-Network Regularized Inverse Design of Frequency-Selective Surface with Frequency-Temporal Deep Learning",
    authors: "Zhu E, Li, Wei, Yin",
    year: 2022,
    venue: "IEEE Transactions on Antennas and Propagation",
    category: "generative",
    domain: "filter",
    training: "unsupervised",
    arxiv: "https://doi.org/10.1109/TAP.2022.3184545",
    tags: ["GAN","AR-FTDL","FSS","frequency-temporal","adversarial","inverse design","dual-polarized"],
    desc: "GAN-regularised inverse design for dual-polarised FSS reducing ambiguity in inverse mapping - AR-FTDL method achieves 79.3% error improvement over direct DNN; cited in MVBPSO.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },
  {
    id: "lyu_mccgan_2025",
    title: "Generative Deep Learning-Enabled Multi-Objective Synthesis of Dual-Polarized Wide-Angle Loop-Family Frequency Selective Surfaces",
    authors: "Lyu, Hong, Chen",
    year: 2025,
    venue: "IEEE Transactions on Antennas and Propagation",
    category: "generative",
    domain: "filter",
    training: "unsupervised",
    arxiv: "",
    tags: ["MC-cGAN","conditional GAN","FSS","dual-polarized","multi-objective","wide-angle","loop","pixel"],
    desc: "Multi-channel conditional GAN (MC-cGAN) for inverse design of dual-polarised wide-angle FSS - extends pixelated inverse design to multi-objective synthesis.",
    cites: ["zhu_arftdl_2022"],
    status: "structured",
  },
  {
    id: "zhang_broadband_apl_2021",
    title: "Deep Learning-Based Design of Broadband GHz Complex and Random Metasurfaces",
    authors: "Zhang T, Kee, Ang L K, Ang Y S",
    year: 2021,
    venue: "APL Photonics",
    category: "deep_learning",
    domain: "general",
    training: "supervised",
    arxiv: "",
    tags: ["CNN","broadband","GHz","complex","random","pixel","metasurface","forward model"],
    desc: "Shows no single DNN model generalises to all metasurface types and each case requires tens of thousands of samples - motivates swarm-guided smart sampling in MVBPSO.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },

  // ===============================================
  //  GENERATIVE MODELS - VAE / GAN / Hybrid-PSO
  // ===============================================

  {
    id: "zhang_vae_pso_2022",
    title: "An Inverse Design Framework for Isotropic Metasurfaces Based on Representation Learning",
    authors: "Zhang J, Yuan, Li C, Li B",
    year: 2022,
    venue: "Electronics",
    category: "generative",
    domain: "filter",
    training: "unsupervised",
    arxiv: "https://doi.org/10.3390/electronics11121844",
    tags: ["VAE","PSO","representation learning","latent space","non-uniqueness","isotropic","16x16 binary pixel","S11","VAE-PSO","STARRY","CST","MATLAB"],
    desc: "STARRY framework: autoencoder RL module maps high-dimensional pixel/response space to low-dimensional latent space; VAE-PSO searches the latent space for optimal binary 16x16 metasurface matrix. Achieves 94% accuracy on test set, design in seconds vs. minutes for GA. Key hybrid combining VAE with swarm optimisation on pixelated binary matrices.",
    cites: ["kennedy_pso_1995","liu_tandem_2018","ma_probabilistic_2019"],
    status: "structured",
  },
  {
    id: "ma_probabilistic_2019",
    title: "Probabilistic Representation and Inverse Design of Metamaterials Based on a Deep Generative Model with Semi-Supervised Learning",
    authors: "Ma, Cheng, Xu, Wen, Liu",
    year: 2019,
    venue: "Advanced Materials",
    category: "generative",
    domain: "general",
    training: "unsupervised",
    arxiv: "https://doi.org/10.1002/adma.201901111",
    tags: ["VAE","semi-supervised","latent space","pixel","multi-solution","generative"],
    desc: "VAE encodes pixelated metamaterial designs into a latent space and generates multiple valid designs per target spectrum - foundational generative inverse design paper.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },
  {
    id: "jiang_gan_metagrating_2019",
    title: "Free-Form Diffractive Metagrating Design Based on Generative Adversarial Networks",
    authors: "Jiang, Fan",
    year: 2019,
    venue: "ACS Nano",
    category: "generative",
    domain: "beam_steering",
    training: "unsupervised",
    arxiv: "https://doi.org/10.1021/acsnano.9b02371",
    tags: ["GAN","pixel metagrating","diffraction","freeform","one-to-many"],
    desc: "GAN generates free-form binary pixel metagrating patterns targeting specified diffraction efficiencies - handles one-to-many mapping for pixelated designs.",
    cites: ["ma_probabilistic_2019"],
    status: "structured",
  },
  {
    id: "kim_vae_latent_2024",
    title: "An Optimization Approach Based on Separated Latent Space for Inverse Design of Metasurfaces",
    authors: "Kim, Hong",
    year: 2024,
    venue: "IEEE Antennas and Wireless Propagation Letters",
    category: "generative",
    domain: "general",
    training: "unsupervised",
    arxiv: "",
    tags: ["VAE","latent space","optimization","separated","inverse design","MSE 2-10%"],
    desc: "Hybrid VAE with latent-space optimisation achieving normalised MSE 2-10% - cited in MVBPSO as deep generative model comparison.",
    cites: ["ma_probabilistic_2019","zhang_vae_pso_2022"],
    status: "structured",
  },
  {
    id: "so_cvae_2020",
    title: "Deep Learning Enabled Inverse Design in Nanophotonics",
    authors: "So, Badloe, Noh, Bravo-Abad, Rho",
    year: 2020,
    venue: "Nanophotonics",
    category: "generative",
    domain: "general",
    training: "unsupervised",
    arxiv: "https://doi.org/10.1515/nanoph-2019-0474",
    tags: ["CVAE","review","inverse design","deep learning","nanophotonics","pixel"],
    desc: "Review of DNN-based inverse design covering tandem, generative models, and surrogate-accelerated optimisation for nanostructures/metasurfaces; includes cVAE achieving MSE ~5-10%.",
    cites: ["liu_tandem_2018","ma_probabilistic_2019"],
    status: "structured",
  },
  {
    id: "tanriover_xgan_2022",
    title: "Deep Generative Modeling and Inverse Design of Manufacturable Free-Form Dielectric Metasurfaces",
    authors: "Tanriover, Lee, Chen, Aydin",
    year: 2022,
    venue: "ACS Photonics",
    category: "generative",
    domain: "general",
    training: "unsupervised",
    arxiv: "",
    tags: ["extended-XGAN","FResNET","freeform","dielectric","manufacturable","97% accuracy"],
    desc: "Extended-XGAN + FResNET for free-form dielectric metasurface generation achieving ~97% accuracy - cited in MVBPSO as deep generative model with complex architecture.",
    cites: ["ma_probabilistic_2019","jiang_gan_metagrating_2019"],
    status: "structured",
  },

  // ===============================================
  //  ACTIVE LEARNING / SMART SAMPLING
  // ===============================================

  {
    id: "ajmi_acdl_2024",
    title: "Prediction Enhancement of Metasurface Absorber Design Using Adaptive Cascaded Deep Learning (ACDL) Model",
    authors: "Ajmi, Bait-Suwailam, Khriji, Al-Lawati",
    year: 2024,
    venue: "Electronics",
    category: "deep_learning",
    domain: "absorber",
    training: "supervised",
    arxiv: "",
    tags: ["active learning","cascaded DNN","adaptive sampling","absorber","pixel","94% accuracy","7000 samples"],
    desc: "Adaptively sampled cascaded DNN reaches ~94% accuracy using only 7,000 samples - shows data quality outweighs dataset size; motivates smart swarm-based sampling in MVBPSO.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },
  {
    id: "wu_phase_pattern_2022",
    title: "Phase-to-Pattern Inverse Design for a Fast Realization of a Functional Metasurface by Combining a Deep Neural Network and a Genetic Algorithm",
    authors: "Wu, Si, Xu, Niu, Zhuang, Sun, Ding",
    year: 2022,
    venue: "Optics Express",
    category: "hybrid",
    domain: "beam_steering",
    training: "supervised",
    arxiv: "",
    tags: ["DNN","genetic algorithm","phase-to-pattern","pixel","hybrid","fast design","3500 samples"],
    desc: "DNN trained on 3,500 samples guides GA and reduces convergence time - demonstrates small-dataset hybrid approach referenced as smart-sampling baseline in MVBPSO.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },
  {
    id: "wang_neutron_2022",
    title: "NEUTRON: Neural Particle Swarm Optimization for Material-Aware Inverse Design of Structural Color",
    authors: "Wang, Guo",
    year: 2022,
    venue: "iScience",
    category: "hybrid",
    domain: "general",
    training: "supervised",
    arxiv: "",
    tags: ["neural PSO","particle swarm","material-aware","structural color","400k dataset","smart sampling"],
    desc: "NEUTRON creates a 400,000-sample dataset via PSO enabling accurate design without random sampling - large-scale swarm-based smart sampling for neural network training.",
    cites: ["kennedy_pso_1995","liu_tandem_2018"],
    status: "structured",
  },
  {
    id: "singh_active_2025",
    title: "Active Learning for Efficient Nanophotonics Inverse Design in Large and Diverse Design Spaces",
    authors: "Singh, Kumar, Singh, Hegde",
    year: 2025,
    venue: "Optics Express",
    category: "hybrid",
    domain: "general",
    training: "supervised",
    arxiv: "",
    tags: ["active learning","CNN","82% fewer simulations","nanophotonics","efficient","diverse"],
    desc: "Active-learning CNN achieves similar accuracy to random sampling while using 82% fewer simulations - key reference motivating guided dataset generation in MVBPSO.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },

  // ===============================================
  //  DIRECT BINARY SEARCH / TOPOLOGY OPTIMIZATION
  // ===============================================

  {
    id: "sell_freeform_2017",
    title: "Large-Area Free-Form Chiral Metalenses",
    authors: "Sell, Yang, Doshay, Yang, Zhang, Fan",
    year: 2017,
    venue: "Nano Letters",
    category: "optimization",
    domain: "lens_hologram",
    training: "supervised",
    arxiv: "",
    tags: ["topology optimization","binary pixel","chiral","metalens","freeform","adjoint"],
    desc: "Topology optimisation on a binary pixel grid to design large-area chiral metalenses - key reference establishing pixel-level TO for complex EM responses.",
    cites: [],
    status: "structured",
  },
  {
    id: "molesky_review_2018",
    title: "Inverse Design in Nanophotonics",
    authors: "Molesky, Lin, Piggott, Jin, Vuckovic, Rodriguez",
    year: 2018,
    venue: "Nature Photonics",
    category: "optimization",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/1801.01094",
    tags: ["review","adjoint","topology optimization","pixel","gradient-based","nanophotonics"],
    desc: "Landmark review of adjoint methods, topology optimisation, and evolutionary algorithms for nanophotonic inverse design on pixel grids - essential taxonomy reference.",
    cites: ["sell_freeform_2017"],
    status: "structured",
  },
  {
    id: "elsawy_num_review_2020",
    title: "Numerical Optimization Methods for Metasurfaces",
    authors: "Elsawy, Lanteri, Duvigneau, Fan, Genevet",
    year: 2020,
    venue: "Laser & Photonics Reviews",
    category: "optimization",
    domain: "general",
    training: "supervised",
    arxiv: "",
    tags: ["review","numerical optimization","adjoint","DE","GA","PSO","metasurface"],
    desc: "Comprehensive review of numerical optimisation (adjoint, DE, GA, PSO) for metasurface design - covers pixel and parameterised approaches; cited widely in BPSO and MVBPSO works.",
    cites: ["molesky_review_2018"],
    status: "structured",
  },

  // ===============================================
  //  REINFORCEMENT LEARNING
  // ===============================================

  {
    id: "sajedian_rl_absorber_2019",
    title: "Finding the Best Design Parameters for Optical Nanostructures Using Reinforcement Learning",
    authors: "Sajedian, Badloe, Rho",
    year: 2019,
    venue: "Optics Express",
    category: "deep_learning",
    domain: "absorber",
    training: "reinforcement",
    arxiv: "https://arxiv.org/abs/1810.10964",
    tags: ["reinforcement learning","Q-learning","absorber","pixel geometry","no labeled data"],
    desc: "RL agent navigates pixel geometry parameter space to optimise absorber designs without surrogate - no labelled training data required.",
    cites: [],
    status: "structured",
  },
  {
    id: "shi_rl_meta_2022",
    title: "Inverse Design of Metasurfaces Using Reinforcement Learning",
    authors: "Shi, Fu, Chen, Torquato",
    year: 2022,
    venue: "ACS Photonics",
    category: "deep_learning",
    domain: "general",
    training: "reinforcement",
    arxiv: "",
    tags: ["reinforcement learning","pixel flipping","Q-learning","no labeled data","metasurface"],
    desc: "RL agent sequentially flips pixels on metasurface grid guided by EM simulation reward - bypasses labelled training data entirely.",
    cites: ["liu_tandem_2018"],
    status: "structured",
  },

  // ===============================================
  //  TERNARY / MULTI-STATE PIXEL
  // ===============================================

  {
    id: "hojjati_ternary_2021",
    title: "Ternary Optimization for Designing Metasurfaces",
    authors: "Hojjati, Soleimani, Nayyeri, Ramahi",
    year: 2021,
    venue: "Scientific Reports",
    category: "optimization",
    domain: "general",
    training: "supervised",
    arxiv: "",
    tags: ["ternary","three-state pixel","PSO","metasurface","ring","Jerusalem cross","slot"],
    desc: "Extends binary pixel PSO to ternary states (no metal / square patch / complex geometry like rings or Jerusalem cross slots) - direct method basis for CP-PIM dataset in MVBPSO.",
    cites: ["kennedy_pso_1995","cui_coding_2014"],
    status: "structured",
  },
  {
    id: "zhang_spacetime_2018",
    title: "Space-Time-Coding Digital Metasurfaces",
    authors: "Zhang, Liu, Wan, Cui",
    year: 2018,
    venue: "Nature Communications",
    category: "analytical",
    domain: "beam_steering",
    training: "supervised",
    arxiv: "https://doi.org/10.1038/s41467-018-06802-0",
    tags: ["space-time coding","dynamic pixel","1-bit","harmonic","programmable"],
    desc: "Extends binary pixel coding into time domain for programmable harmonic control and beam steering with binary pixel switching sequences.",
    cites: ["cui_coding_2014"],
    status: "structured",
  },

  // ===============================================
  //  RIS / RECONFIGURABLE INTELLIGENT SURFACE
  // ===============================================

  {
    id: "li_reprogrammable_2019",
    title: "Machine-Learning Reprogrammable Metasurface Imager",
    authors: "Li, Shuang, Cheng, Li, Peng et al.",
    year: 2019,
    venue: "Nature Communications",
    category: "hybrid",
    domain: "sensing",
    training: "supervised",
    arxiv: "https://doi.org/10.1038/s41467-019-09103-2",
    tags: ["programmable","1-bit pixel","machine learning","computational imaging","microwave","RIS"],
    desc: "1-bit pixel coding metasurface combined with ML for reprogrammable computational microwave imaging - pixel-level real-time adaptation for sensing applications.",
    cites: ["cui_coding_2014"],
    status: "structured",
  },

  // ══════ Auto-added 2026-07-01 ══════
  {
    id: "multifunctional_imaging_with_an_inverse_2026",
    title: "Multifunctional Imaging with an Inverse-Designed Nonlocal Metasurface",
    authors: "Clark, Xu, Phan et al.",
    year: 2026,
    venue: "Preprint",
    category: "hybrid",
    domain: "microwave",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2606.21051",
    tags: [],
    desc: "Nonlocal metasurfaces enable all-optical processing of spatial information in optical fields. Here, we demonstrate a topology-optimised metasurface that switches between phase-contrast and brightfield imaging modalities …",
    cites: [],
  },
  {
    id: "inverse_design_of_realizable_metasurface_2026",
    title: "Inverse Design of Realizable Metasurface based Absorbers using Improved Conditioning and Diversity Enhanced Progressively Growing GANs",
    authors: "Joy, Abdullah, Pal et al.",
    year: 2026,
    venue: "Preprint",
    category: "generative",
    domain: "microwave",
    training: "unsupervised",
    arxiv: "https://arxiv.org/abs/2606.05849",
    tags: [],
    desc: "Metasurfaces enable precise manipulation of electromagnetic waves for applications such as beam steering, sensing, and stealth technology. However, inverse design of metasurfaces with targeted EM responses remains challe…",
    cites: [],
  },
  {
    id: "multi_wavelength_polarisation_imaging_wi_2026",
    title: "Multi-wavelength polarisation imaging with inverse designed metasurfaces",
    authors: "Dean, Li, Munro et al.",
    year: 2026,
    venue: "Preprint",
    category: "deep_learning",
    domain: "microwave",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2604.27756",
    tags: [],
    desc: "Multispectral polarisation imaging has a broad range of applications, from biological cell imaging to agricultural remote surveying. For such applications, especially involving lightweight unmanned aerial vehicles like d…",
    cites: [],
  },
  {
    id: "inverse_designed_full_stokes_polarimetri_2026",
    title: "Inverse designed full-Stokes polarimetric metasurface with simultaneous wavefront sensing for visible light",
    authors: "Červinka, Hrtoň, Venos et al.",
    year: 2026,
    venue: "Preprint",
    category: "deep_learning",
    domain: "lens_hologram",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2604.18879",
    tags: [],
    desc: "Metasurfaces have emerged as a powerful platform for compact optical sensors by replacing bulky lenses with flat arrays of subwavelength nanostructures. In precision optical metrology, the simultaneous mapping of a beam'…",
    cites: [],
  },
  {
    id: "end_to_end_inverse_designed_single_layer_2026",
    title: "End-to-End Inverse Designed Single-Layered Metasurface for High-Compression Snapshot RGB-Achromatic Full-Stokes Polarization Imaging",
    authors: "Chai, Bao, Yang et al.",
    year: 2026,
    venue: "Preprint",
    category: "deep_learning",
    domain: "sensing",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2604.14901",
    tags: [],
    desc: "Snapshot full-Stokes polarimetry across multiple wavelengths remains challenging because conventional architectures rely on multiplexed measurements and bulky optics. We present an end-to-end inverse designed single-laye…",
    cites: [],
  },
  {
    id: "inverse_designed_metasurfaces_for_compac_2026",
    title: "Inverse-Designed Metasurfaces for Compact Optical Skyrmion Generation with High Topological Fidelity",
    authors: "Park, Song, Chung et al.",
    year: 2026,
    venue: "Preprint",
    category: "optimization",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2603.23922",
    tags: [],
    desc: "Optical skyrmions are structured vector fields with nontrivial polarization topology and subwavelength-scale features. One common approach to generating optical skyrmions is the superposition of a zeroth-order Bessel bea…",
    cites: [],
  },
  {
    id: "harnessing_selective_state_space_models_2026",
    title: "Harnessing Selective State Space Models to Enhance Semianalytical Design of Fabrication-Ready Multilayered Huygens' Metasurfaces: Part II - Generative Inverse Design (MetaMamba)",
    authors: "Nissan, Marcus, Raviv et al.",
    year: 2026,
    venue: "Preprint",
    category: "optimization",
    domain: "microwave",
    training: "unsupervised",
    arxiv: "https://arxiv.org/abs/2603.03877",
    tags: [],
    desc: "We present a generative framework for inverse design of five-layer transmissive Huygens' metasurfaces (HMSs), addressing a longstanding challenge in achieving full-phase, high-efficiency unit cell designs with minimal fu…",
    cites: [],
  },
  {
    id: "accelerating_inverse_design_of_optical_m_2026",
    title: "Accelerating Inverse Design of Optical Metasurfaces: Analytic Gradients of Periodic Green's Functions via Quasi-Modular Forms",
    authors: "Qin, Qin",
    year: 2026,
    venue: "Preprint",
    category: "analytical",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2603.03755",
    tags: [],
    desc: "The inverse design of nonlocal metasurfaces requires the precise optimization of lattice geometry to engineer spatial dispersion and high-Q resonances. However, gradient-based optimization is frequently bottle-necked by …",
    cites: [],
  },
  {
    id: "diffusion_schr_dinger_bridges_with_enhan_2026",
    title: "Diffusion Schrödinger Bridges with enhanced posterior sampling for metasurface inverse design",
    authors: "Grand, Urard, Rideau et al.",
    year: 2026,
    venue: "Preprint",
    category: "hybrid",
    domain: "general",
    training: "unsupervised",
    arxiv: "https://arxiv.org/abs/2602.06605",
    tags: [],
    desc: "Metasurface inverse design is challenged by the intricate relationship between structural parameters and electromagnetic responses, as well as the high dimensionality of the optimization space. Local models, while common…",
    cites: [],
  },
  {
    id: "inverse_design_of_tunable_infrared_metas_2026",
    title: "Inverse Design of Tunable Infrared Metasurface Absorbers via a Conditional Wasserstein Generative Adversarial Network",
    authors: "Shen, Wang, Yao et al.",
    year: 2026,
    venue: "Preprint",
    category: "generative",
    domain: "absorber",
    training: "unsupervised",
    arxiv: "https://arxiv.org/abs/2602.03062",
    tags: [],
    desc: "Narrowband perfect absorbers are interesting for spectrum sensing, molecular detection, and infrared imaging. However, their design remains constrained by intuitive, iterative methods that lack flexibility, while also fa…",
    cites: [],
  },
  {
    id: "enhanced_posterior_sampling_via_diffusio_2026",
    title: "Enhanced posterior sampling via diffusion models for efficient metasurfaces inverse design",
    authors: "Grand, Urard, Rideau et al.",
    year: 2026,
    venue: "Preprint",
    category: "generative",
    domain: "general",
    training: "unsupervised",
    arxiv: "https://arxiv.org/abs/2601.15210",
    tags: [],
    desc: "The inverse design of metasurfaces faces inherent challenges due to the nonlinear and highly complex relationship between geometric configurations and their electromagnetic behavior. Traditional optimization approaches o…",
    cites: [],
  },
  {
    id: "deep_learning_enabled_inverse_design_of_2025",
    title: "Deep-learning-enabled inverse design of large-scale metasurfaces with full-wave accuracy",
    authors: "Xu, Shao, Zhao et al.",
    year: 2025,
    venue: "Preprint",
    category: "deep_learning",
    domain: "lens_hologram",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2512.12625",
    tags: [],
    desc: "Recent advances in meta-optics have enabled diverse functionalities in compact optical devices; however, conventional forward design approaches become inadequate as device complexity and scale grow. Inverse design offers…",
    cites: [],
  },
  {
    id: "intelligent_inverse_design_of_multi_laye_2025",
    title: "Intelligent Inverse Design of Multi-Layer Metasurface Cavities for Dual Resonance Enhancement of Nanodiamond Single Photon Emitters",
    authors: "Abdelraouf",
    year: 2025,
    venue: "Preprint",
    category: "deep_learning",
    domain: "sensing",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2511.15170",
    tags: [],
    desc: "Single-photon emitters (SPEs) based on nitrogen-vacancy centers in nanodiamonds (neutral NV0 (wavelength 575 nm) and negative NV- (wavelength 637 nm)) represent promising platforms for quantum nanophotonics applications,…",
    cites: [],
  },
  {
    id: "uniform_2d_target_generation_via_inverse_2025",
    title: "Uniform 2D Target Generation via Inverse-designed Metasurfaces",
    authors: "Zhou, Chen, Zhao",
    year: 2025,
    venue: "Preprint",
    category: "optimization",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2509.16192",
    tags: [],
    desc: "We propose an inverse design framework for metasurfaces that achieves highly uniform two-dimensional intensity profiles across an on-demand shape. The optimization objective is formulated to enhance overall projection ef…",
    cites: [],
  },
  {
    id: "inverse_design_using_physics_informed_qu_2025",
    title: "Inverse Design using Physics-Informed Quantum GANs for Tailored Absorption in Dielectric Metasurfaces",
    authors: "Warrier, Dontabhaktuni",
    year: 2025,
    venue: "Preprint",
    category: "generative",
    domain: "microwave",
    training: "unsupervised",
    arxiv: "https://arxiv.org/abs/2507.18132",
    tags: [],
    desc: "High Q-factor narrow-band absorption exhibits high spectral selectivity enabling high-sensitive photodetectors, sensors and thermal emitters. All-dielectric metasurfaces are widely regarded as excellent candidates for gi…",
    cites: [],
  },
  {
    id: "hybrid_quantum_classical_inverse_design_2025",
    title: "Hybrid Quantum-Classical Inverse Design of Metasurfaces for Tailored Narrow Band Absorption",
    authors: "Warrier, Dontabhaktuni",
    year: 2025,
    venue: "Preprint",
    category: "generative",
    domain: "microwave",
    training: "unsupervised",
    arxiv: "https://arxiv.org/abs/2507.18127",
    tags: [],
    desc: "The inverse design of metasurfaces poses a considerable challenge because of the intricate interdependencies that exist between structural characteristics and electromagnetic responses. Traditional optimization methods r…",
    cites: [],
  },
  {
    id: "hybrid_quantum_generative_adversarial_ne_2025",
    title: "Hybrid Quantum Generative Adversarial Networks To Inverse Design Metasurfaces For Incident Angle-Independent Unidirectional Transmission",
    authors: "Warrier, Dontabhaktuni",
    year: 2025,
    venue: "Preprint",
    category: "generative",
    domain: "beam_steering",
    training: "unsupervised",
    arxiv: "https://arxiv.org/abs/2507.03518",
    tags: [],
    desc: "Optimization of metasurface designs for specific functionality is a challenging problem due to the intricate relation between structural features and electromagnetic responses. Recently, many researchers resolved to inve…",
    cites: [],
  },
  {
    id: "inverse_design_of_diffractive_metasurfac_2025",
    title: "Inverse Design of Diffractive Metasurfaces Using Diffusion Models",
    authors: "Hen, Yosef, Raviv et al.",
    year: 2025,
    venue: "Preprint",
    category: "generative",
    domain: "beam_steering",
    training: "unsupervised",
    arxiv: "https://arxiv.org/abs/2506.21748",
    tags: [],
    desc: "Metasurfaces are ultra-thin optical elements composed of engineered sub-wavelength structures that enable precise control of light. Their inverse design - determining a geometry that yields a desired optical response - i…",
    cites: [],
  },
  {
    id: "inverse_designed_metasurfaces_for_wavefr_2025",
    title: "Inverse-Designed Metasurfaces for Wavefront Restoration in Under-Display Camera Systems",
    authors: "Jo, Lee, Lee et al.",
    year: 2025,
    venue: "Preprint",
    category: "deep_learning",
    domain: "sensing",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2504.17368",
    tags: [],
    desc: "Under-display camera (UDC) systems enable full-screen displays in smartphones by embedding the camera beneath the display panel, eliminating the need for notches or punch holes. However, the periodic pixel structures of …",
    cites: [],
  },
  {
    id: "metasurfacevit_a_generic_ai_model_for_me_2025",
    title: "MetasurfaceViT: A generic AI model for metasurface inverse design",
    authors: "Yan, Yi, Ma et al.",
    year: 2025,
    venue: "Preprint",
    category: "deep_learning",
    domain: "lens_hologram",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2504.14895",
    tags: [],
    desc: "Metasurfaces, sub-wavelength artificial structures, can control light's amplitude, phase, and polar ization, enabling applications in efficient imaging, holograms, and sensing. Recent years, AI has witnessed remarkable p…",
    cites: [],
  },
  {
    id: "computational_inverse_design_of_acoustop_2025",
    title: "Computational inverse design of acoustoplasmonic metasurfaces",
    authors: "Holland, Boechler, Poulikakos",
    year: 2025,
    venue: "Preprint",
    category: "optimization",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2504.07211",
    tags: [],
    desc: "Optical and acoustic metasurfaces are two-dimensional arrays of subwavelength elements that locally modulate or phase shift incident waves. Acoustoplasmonic metasurfaces combine the physics of light and sound, producing …",
    cites: [],
  },
  {
    id: "expressivity_of_programmable_metasurface_2026",
    title: "Expressivity of Programmable-Metasurface-Based Physical Neural Networks: Encoding Non-Linearity, Structural Non-Linearity, and Depth",
    authors: "Hammami, Magoarou, Monochristou et al.",
    year: 2026,
    venue: "Preprint",
    category: "deep_learning",
    domain: "microwave",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2603.13602",
    tags: [],
    desc: "Wave-based signal processing conventionally encodes input data into the input wavefront, making it challenging to implement non-linear operations. Programmable wave systems enable an alternative approach: encoding the in…",
    cites: [],
  },
  {
    id: "metasurfaces_integrated_wireless_neural_2026",
    title: "Metasurfaces-Integrated Wireless Neural Networks for Lightweight Over-The-Air Edge Inference",
    authors: "Stylianopoulos, Pandolfo, Lorenzo et al.",
    year: 2026,
    venue: "Preprint",
    category: "deep_learning",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2602.19312",
    tags: [],
    desc: "The upcoming sixth Generation (6G) of wireless networks envisions ultra-low latency and energy efficient Edge Inference (EI) for diverse Internet of Things (IoT) applications. However, traditional digital hardware for ma…",
    cites: [],
  },
  {
    id: "integrating_stacked_intelligent_metasurf_2025",
    title: "Integrating Stacked Intelligent Metasurfaces and Power Control for Dynamic Edge Inference via Over-The-Air Neural Networks",
    authors: "Stylianopoulos, Alexandropoulos",
    year: 2025,
    venue: "Preprint",
    category: "deep_learning",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2509.18906",
    tags: [],
    desc: "This paper introduces a novel framework for Edge Inference (EI) that bypasses the conventional practice of treating the wireless channel as noise. We utilize Stacked Intelligent Metasurfaces (SIMs) to control wireless pr…",
    cites: [],
  },
  {
    id: "onboard_terrain_classification_via_stack_2025",
    title: "Onboard Terrain Classification via Stacked Intelligent Metasurface-Diffractive Deep Neural Networks from SAR Level-0 Raw Data",
    authors: "Liu, Li, An et al.",
    year: 2025,
    venue: "Preprint",
    category: "deep_learning",
    domain: "sensing",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2503.13488",
    tags: [],
    desc: "This paper introduces a novel approach for real-time onboard terrain classification from Sentinel-1 (S1) level-0 raw In-phase/Quadrature (IQ) data, leveraging a Stacked Intelligent Metasurface (SIM) to perform inference …",
    cites: [],
  },
  {
    id: "beyond_the_limits_of_rigid_arrays_flexib_2026",
    title: "Beyond the Limits of Rigid Arrays: Flexible Intelligent Metasurfaces for Next-Generation Wireless Networks",
    authors: "Magbool, Kumar, Renzo et al.",
    year: 2026,
    venue: "Preprint",
    category: "hybrid",
    domain: "sensing",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2603.11886",
    tags: [],
    desc: "Following recent advances in flexible electronics and programmable metasurfaces, flexible intelligent metasurfaces (FIMs) have emerged as a promising enabling technology for next-generation wireless networks. A FIM is a …",
    cites: [],
  },
  {
    id: "in_wave_computation_aided_stacked_intell_2026",
    title: "In-Wave Computation Aided Stacked Intelligent Metasurfaces in Next-Generation Networks: Challenges and Opportunities",
    authors: "Liu, Yuen, Niyato et al.",
    year: 2026,
    venue: "Preprint",
    category: "hybrid",
    domain: "microwave",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2603.05892",
    tags: [],
    desc: "Stacked intelligent metasurfaces (SIMs) facilitate computation by cascaded programmable layers so that part of the signal processing can be performed in the wave domain during signal propagation, rather than solely after…",
    cites: [],
  },
  {
    id: "meta_gpt_decoding_the_metasurface_genome_2025",
    title: "Meta-GPT: Decoding the Metasurface Genome with Generative Artificial Intelligence",
    authors: "Dang, Love, Salib et al.",
    year: 2025,
    venue: "Preprint",
    category: "deep_learning",
    domain: "general",
    training: "unsupervised",
    arxiv: "https://arxiv.org/abs/2512.12888",
    tags: [],
    desc: "Advancing artificial intelligence for physical sciences requires representations that are both interpretable and compatible with the underlying laws of nature. We introduce METASTRINGS, a symbolic language for photonics …",
    cites: [],
  },
  {
    id: "design_and_optimization_of_an_azo_based_2026",
    title: "Design and optimization of an AZO-based plasmonic metasurface-driven optical solar reflector for thermal management",
    authors: "Viseur, Mayer, Henrard et al.",
    year: 2026,
    venue: "Preprint",
    category: "optimization",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2606.12957",
    tags: [],
    desc: "Plasmonic metasurface-driven Optical Solar Reflectors (m-OSRs) offer a promising route towards lightweight and high-performance thermal management. By exploiting subwavelength structuring and intrinsic material losses, s…",
    cites: [],
  },
  {
    id: "from_multi_port_models_to_cascade_struct_2026",
    title: "From Multi-Port Models to Cascade Structures: Optimization of Active Unilateral Stacked Intelligent Metasurfaces",
    authors: "Abrardo, Bartoli, Toccafondi et al.",
    year: 2026,
    venue: "Preprint",
    category: "deep_learning",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2605.05884",
    tags: [],
    desc: "This paper develops a multi-port S-parameter framework for the analysis and optimization of stacked intelligent metasurfaces (SIMs) with unilateral active interconnections. By modeling each unit cell as a non-reciprocal …",
    cites: [],
  },
  {
    id: "2d_waveguide_fed_metasurfaces_physically_2026",
    title: "2D Waveguide-Fed Metasurfaces: Physically Consistent Modeling, Validation, and Optimization",
    authors: "Gavriilidis, Alexandropoulos",
    year: 2026,
    venue: "Preprint",
    category: "analytical",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2605.02400",
    tags: [],
    desc: "Antenna array architectures based on programmable metasurfaces are emerging as a promising solution for scalable implementations of the eXtremely Large Multiple-Input Multiple-Output (XL-MIMO) systems paradigm, envisione…",
    cites: [],
  },
  {
    id: "optimizing_dynamic_metasurface_antenna_c_2026",
    title: "Optimizing Dynamic Metasurface Antenna Configurations for Direction-of-Arrival and Polarization Estimation Using an Experimentally Calibrated Multiport-Network Model",
    authors: "Tapie, Hougne",
    year: 2026,
    venue: "Preprint",
    category: "optimization",
    domain: "sensing",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2604.26948",
    tags: [],
    desc: "Sensing the direction of arrival and polarization of impinging signals is a key prerequisite for beamforming and interference mitigation in modern wireless communication systems. Dynamic metasurface antennas (DMAs) can m…",
    cites: [],
  },
  {
    id: "simultaneous_unicast_and_multicast_trans_2026",
    title: "Simultaneous Unicast and Multicast Transmissions in Stacked Intelligent Metasurfaces-assisted HAPS Wireless Networks: Performance Analysis and Optimization",
    authors: "Le, Alouini",
    year: 2026,
    venue: "Preprint",
    category: "deep_learning",
    domain: "microwave",
    training: "unsupervised",
    arxiv: "https://arxiv.org/abs/2604.04684",
    tags: [],
    desc: "In this paper, we investigate high-altitude platform station (HAPS) wireless networks for simultaneous non-orthogonal unicast and multicast transmissions. Specifically, stacked intelligent metasurface (SIM)-based wave-do…",
    cites: [],
  },
  {
    id: "modeling_optimization_and_electromagneti_2026",
    title: "Modeling, Optimization and Electromagnetic Validation of Stacked Intelligent Metasurfaces by Using a Multiport Network Model",
    authors: "Pettanice, Abrardo, Toccafondi et al.",
    year: 2026,
    venue: "Preprint",
    category: "deep_learning",
    domain: "microwave",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2603.14266",
    tags: [],
    desc: "Stacked intelligent metasurfaces (SIMs) extend the concept of reconfigurable intelligent surfaces by cascading multiple programmable layers, enabling advanced electromagnetic wave transformations for communication and se…",
    cites: [],
  },
  {
    id: "manufacturable_blazed_metasurface_gratin_2026",
    title: "Manufacturable blazed metasurface gratings designed by 3D topology optimization model",
    authors: "Ans, Zamkotsian, Demésy",
    year: 2026,
    venue: "Preprint",
    category: "optimization",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2603.14013",
    tags: [],
    desc: "We present the generalization of our FEM-based topology optimization framework to 3D blazed metasurfaces operating in reflection over the visible and near-infrared range [400-1,500]nm. The design region is described thro…",
    cites: [],
  },
  {
    id: "secure_high_resolution_isac_via_multi_la_2026",
    title: "Secure High-Resolution ISAC via Multi-Layer Intelligent Metasurfaces: A Layered Optimization Framework",
    authors: "Taherpour, Taherpour, Khattab",
    year: 2026,
    venue: "Preprint",
    category: "deep_learning",
    domain: "sensing",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2602.15209",
    tags: [],
    desc: "Integrated sensing and communication (ISAC) has emerged as a pivotal technology for next-generation wireless networks, enabling simultaneous data transmission and environmental sensing. However, existing ISAC systems fac…",
    cites: [],
  },
  {
    id: "optimizing_spectral_prediction_in_mxene_2026",
    title: "Optimizing Spectral Prediction in MXene-Based Metasurfaces Through Multi-Channel Spectral Refinement and Savitzky-Golay Smoothing",
    authors: "Khan, Waseer",
    year: 2026,
    venue: "Preprint",
    category: "deep_learning",
    domain: "absorber",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2602.08406",
    tags: [],
    desc: "The prediction of electromagnetic spectra for MXene-based solar absorbers is a computationally intensive task, traditionally addressed using full-wave solvers. This study introduces an efficient deep learning framework i…",
    cites: [],
  },
  {
    id: "achievable_rate_optimization_for_large_f_2026",
    title: "Achievable Rate Optimization for Large Flexible Intelligent Metasurface Assisted Downlink MISO under Statistical CSI",
    authors: "He, Kumar, Papazafeiropoulos et al.",
    year: 2026,
    venue: "Preprint",
    category: "deep_learning",
    domain: "microwave",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2601.15471",
    tags: [],
    desc: "The integration of electromagnetic metasurfaces into wireless communications enables intelligent control of the propagation environment. Recently, flexible intelligent metasurfaces (FIMs) have evolved beyond conventional…",
    cites: [],
  },
  {
    id: "optimization_of_the_metal_dielectric_met_2026",
    title: "Optimization of the metal-dielectric metasurface unit cell for sensitivity enhancement in determination of IgG concentration in solutions",
    authors: "Kuznetsova, Pashynska, Eremenko",
    year: 2026,
    venue: "Preprint",
    category: "hybrid",
    domain: "microwave",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2601.05979",
    tags: [],
    desc: "This study focuses on developing a metal-dielectric sensor structure with optimized unit cell geometry for determination of protein Immunoglobulin G (IgG) concentration in aqueous solutions. The research combines both ex…",
    cites: [],
  },
  {
    id: "a_neat_approach_to_evolving_neural_netwo_2025",
    title: "A NEAT Approach to Evolving Neural-Network-based Optimization of Chiral Photonic Metasurfaces: Application of a Neuro-Evolution Pipeline",
    authors: "Filippozzi, Rahimi-Iman",
    year: 2025,
    venue: "Preprint",
    category: "deep_learning",
    domain: "general",
    training: "reinforcement",
    arxiv: "https://arxiv.org/abs/2512.23558",
    tags: [],
    desc: "The design of chiral metasurfaces with tailored optical properties remains a central challenge in nanophotonics due to the highly nonlinear relationship between geometry and chiroptical response. Machine-learning-assiste…",
    cites: [],
  },
  {
    id: "advancing_machine_learning_optimization_2025",
    title: "Advancing Machine Learning Optimization of Chiral Photonic Metasurface: Comparative Study of Neural Network and Genetic Algorithm Approaches",
    authors: "Filippozzi, Mayer, Roy et al.",
    year: 2025,
    venue: "Preprint",
    category: "deep_learning",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2512.13656",
    tags: [],
    desc: "Chiral photonic metasurfaces provide unique capabilities for tailoring light-matter interactions, which are essential for next-generation photonic devices. Here, we report an advanced optimization framework that combines…",
    cites: [],
  },
  {
    id: "near_field_topology_optimized_superchira_2025",
    title: "Near-Field Topology-Optimized Superchiral Metasurfaces for Enhanced Chiral Sensing",
    authors: "Jiang, Sohag, Zhou",
    year: 2025,
    venue: "Preprint",
    category: "hybrid",
    domain: "microwave",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2511.15964",
    tags: [],
    desc: "The detection and discrimination of molecular chirality are essential for advancing pharmaceutical and biological applications. While nanophotonic platforms offer a route to enhance chiral light-matter interactions, exis…",
    cites: [],
  },
  {
    id: "2d_waveguide_fed_metasurface_antenna_arr_2025",
    title: "2D Waveguide-Fed Metasurface Antenna Arrays: Modeling and Optimization for Bistatic Sensing",
    authors: "Gavras, Gavriilidis, Alexandropoulos",
    year: 2025,
    venue: "Preprint",
    category: "deep_learning",
    domain: "sensing",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2511.09254",
    tags: [],
    desc: "This paper presents a physics-consistent framework for bistatic sensing incorporating a 2-Dimensional (2D) waveguide-fed metasurface antenna array capable of realizing eXtremely-Large Multiple-Input Multiple-Output (XL M…",
    cites: [],
  },
  {
    id: "electromagnetics_compliant_optimization_2025",
    title: "Electromagnetics-Compliant Optimization of Dynamic Metasurface Antennas for Bistatic Sensing",
    authors: "Gavras, Alexandropoulos",
    year: 2025,
    venue: "Preprint",
    category: "hybrid",
    domain: "sensing",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2509.19801",
    tags: [],
    desc: "Dynamic Metasurface Antennas (DMAs) are recently attracting considerable research interests due to their potential to enable low-cost, reconfigurable, and highly scalable antenna array architectures for next generation w…",
    cites: [],
  },
  {
    id: "optimization_of_airgap_in_a_monocentric_2025",
    title: "Optimization of airgap in a monocentric lens assembly and metasurface based anti-reflecting coating in the long-wave IR regime",
    authors: "Kala, Singh, Mishra et al.",
    year: 2025,
    venue: "Preprint",
    category: "hybrid",
    domain: "microwave",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2508.12899",
    tags: [],
    desc: "Owing to minimal aberration, larger field-of-view, and high resolution, monocentric lenses are preferred over other imagers in hemispherical image surface scenarios, particularly in the long-wave infrared (LWIR) region. …",
    cites: [],
  },
  {
    id: "metasurfaces_integrated_doubly_dispersiv_2025",
    title: "Metasurfaces-Integrated Doubly-Dispersive MIMO: Channel Modeling and Optimization",
    authors: "Ranasinghe, Rou, Sandoval et al.",
    year: 2025,
    venue: "Preprint",
    category: "deep_learning",
    domain: "microwave",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2506.14985",
    tags: [],
    desc: "The doubly-dispersive (DD) channel structure has played a pivotal role in wireless communications, particularly in high-mobility scenarios and integrated sensing and communications (ISAC), due to its ability to capture t…",
    cites: [],
  },
  {
    id: "broadband_tunable_deep_uv_emission_from_2025",
    title: "Broadband Tunable Deep-UV Emission from AI-Optimized Nonlinear Metasurface Architectures",
    authors: "Abdelraouf",
    year: 2025,
    venue: "Preprint",
    category: "deep_learning",
    domain: "general",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2506.10442",
    tags: [],
    desc: "Metasurfaces represent a pivotal advancement in nonlinear optics, leveraging high-Q resonant cavities to enhance harmonic generation. Multi-layer metasurfaces (MLMs) further amplify this potential by intensifying light-m…",
    cites: [],
  },
  {
    id: "lorentzian_constrained_holographic_beamf_2025",
    title: "Lorentzian-Constrained Holographic Beamforming Optimization in Multi-user Networks with Dynamic Metasurface Antennas",
    authors: "Altinoklu, Musavian",
    year: 2025,
    venue: "Preprint",
    category: "hybrid",
    domain: "lens_hologram",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2505.08356",
    tags: [],
    desc: "Dynamic metasurface antennas (DMAs) are promising alternatives to fully digital (FD) architectures, enabling hybrid beamforming via low-cost reconfigurable metasurfaces. In DMAs, holographic beamforming is achieved throu…",
    cites: [],
  },
  {
    id: "fabrication_optimization_of_van_der_waal_2025",
    title: "Fabrication Optimization of van der Waals Metasurfaces: Inverse Patterning Boosts Resonance Quality Factor",
    authors: "Biechteler, Heimig, Weber et al.",
    year: 2025,
    venue: "Preprint",
    category: "hybrid",
    domain: "sensing",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2503.17128",
    tags: [],
    desc: "Van der Waals (vdW) materials have garnered growing interest for use as nanophotonic building blocks that offer precise control over light-matter interaction at the nanoscale, such as optical metasurfaces hosting sharp q…",
    cites: [],
  },
  {
    id: "double_metasurfaces_and_optimal_transpor_2025",
    title: "Double metasurfaces and Optimal transport",
    authors: "Altiner, Gutiérrez",
    year: 2025,
    venue: "Preprint",
    category: "hybrid",
    domain: "lens_hologram",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2503.04536",
    tags: [],
    desc: "This paper constructs metalenses that separate homogeneous media with different refractive indices, refracting one domain into another while conserving a prescribed energy distribution. Using optimal transport theory, we…",
    cites: [],
  },
  {
    id: "topology_optimization_of_a_superabsorbin_2025",
    title: "Topology optimization of a superabsorbing thin-film semiconductor metasurface",
    authors: "Gedeon, Allayarov, Hassan et al.",
    year: 2025,
    venue: "Preprint",
    category: "optimization",
    domain: "absorber",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2502.19352",
    tags: [],
    desc: "We demonstrate a computational inverse design method for optimizing broadband-absorbing metasurfaces made of arbitrary dispersive media. Our figure of merit is the time-averaged instantaneous power dissipation in a singl…",
    cites: [],
  },
  {
    id: "improving_generative_inverse_design_of_r_2025",
    title: "Improving Generative Inverse Design of Rectangular Patch Antennas with Test Time Optimization",
    authors: "LaBash, Khushrushahi, Ruehle",
    year: 2025,
    venue: "Preprint",
    category: "deep_learning",
    domain: "antenna",
    training: "unsupervised",
    arxiv: "https://arxiv.org/abs/2505.18188",
    tags: [],
    desc: "We propose a two-stage deep learning framework for the inverse design of rectangular patch antennas. Our approach leverages generative modeling to learn a latent representation of antenna frequency response curves and co…",
    cites: [],
  },
  {
    id: "model_based_deep_learning_tuning_of_reco_2025",
    title: "Model-Based Deep Learning Tuning of Reconfigurable Intelligent Surface for OFDM Radar Interference Mitigation",
    authors: "Parchekani, Johnny, Valaee",
    year: 2025,
    venue: "Preprint",
    category: "deep_learning",
    domain: "microwave",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2504.04580",
    tags: [],
    desc: "This paper presents a deep learning-based framework for enhancing radar systems in the presence of interference, leveraging Reconfigurable Intelligent Surfaces (RIS). The proposed technique uses a modified MUSIC algorith…",
    cites: [],
  },
  {
    id: "prototype_aware_fundamental_electromagne_2026",
    title: "Prototype-Aware Fundamental Electromagnetic Limits on Wavefront Synthesis with Programmable Metasurfaces",
    authors: "Hougne",
    year: 2026,
    venue: "Preprint",
    category: "hybrid",
    domain: "microwave",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2606.14944",
    tags: [],
    desc: "Wavefront synthesis is a central objective in many applications of programmable metasurfaces (PMs), ranging from electromagnetic holography and computational imaging to massive backscatter communications. Yet, fundamenta…",
    cites: [],
  },
  {
    id: "multi_functional_programmable_metasurfac_2025",
    title: "Multi-Functional Programmable Metasurfaces for 6G and Beyond",
    authors: "Gan, Mu, Liu et al.",
    year: 2025,
    venue: "Preprint",
    category: "deep_learning",
    domain: "sensing",
    training: "supervised",
    arxiv: "https://arxiv.org/abs/2512.06693",
    tags: [],
    desc: "The sixth-generation and beyond (B6G) networks are envisioned to support advanced applications that demand high-speed communication, high-precision sensing, and high-performance computing. To underpin this multi-function…",
    cites: [],
  },
];

// Build edges from cites
const EDGES = [];
const _idSet = new Set(PAPERS.map(p => p.id));
PAPERS.forEach(p => {
  (p.cites || []).forEach(cid => {
    if (_idSet.has(cid)) EDGES.push({ source: p.id, target: cid });
  });
});
