// ─────────────────────────────────────────────
//  wm_papers — World Model Papers Database
// ─────────────────────────────────────────────
const PAPERS = [
  // ══════ 2018 ══════
  {
    id: "world_models_2018",
    title: "World Models",
    authors: "Ha, Schmidhuber",
    year: 2018,
    venue: "NeurIPS",
    category: "latent",
    domain: "gaming",
    training: "online",
    arxiv: "https://arxiv.org/abs/1803.10122",
    tags: ["VAE", "RNN", "MDN"],
    desc: "VAE + MDN-RNN for learning environment dynamics in latent space. Foundational work that kicked off modern world model research.",
    cites: ["dreamer_2020", "simpl_2019"],
  },
  // ══════ 2019 ══════
  {
    id: "simpl_2019",
    title: "SimPLe: Model-Based RL via Simulated Policy Learning",
    authors: "Kaiser et al.",
    year: 2019,
    venue: "ICLR",
    category: "autoregressive",
    domain: "gaming",
    training: "online",
    arxiv: "https://arxiv.org/abs/1903.00374",
    tags: ["Atari", "video prediction", "sample efficiency"],
    desc: "Learns a video prediction model and trains policies inside it for Atari games.",
    cites: ["dreamer_2020"],
  },
  {
    id: "planet_2019",
    title: "Learning Latent Dynamics for Planning from Pixels",
    authors: "Hafner et al.",
    year: 2019,
    venue: "ICML",
    category: "latent",
    domain: "general",
    training: "online",
    arxiv: "https://arxiv.org/abs/1811.04551",
    tags: ["RSSM", "planning", "CEM"],
    desc: "PlaNet: learns latent dynamics with RSSM and plans via CEM in latent space. Precursor to Dreamer.",
    cites: ["dreamer_2020"],
  },
  // ══════ 2020 ══════
  {
    id: "dreamer_2020",
    title: "Dream to Control: Learning Behaviors by Latent Imagination",
    authors: "Hafner et al.",
    year: 2020,
    venue: "ICLR",
    category: "latent",
    domain: "general",
    training: "online",
    arxiv: "https://arxiv.org/abs/1912.01603",
    tags: ["RSSM", "actor-critic", "imagination"],
    desc: "Learns latent dynamics with RSSM and trains actor-critic purely in imagination.",
    cites: ["dreamerv2_2021", "dreamerv3_2023"],
  },
  {
    id: "muzero_2020",
    title: "Mastering Atari, Go, Chess and Shogi by Planning with a Learned Model",
    authors: "Schrittwieser et al.",
    year: 2020,
    venue: "Nature",
    category: "latent",
    domain: "gaming",
    training: "online",
    arxiv: "https://arxiv.org/abs/1911.08265",
    tags: ["MCTS", "planning", "value prediction"],
    desc: "Learns a model that predicts rewards, values, and policies for tree search planning.",
    cites: ["efficientzero_2022", "td_mpc_2022"],
  },
  // ══════ 2021 ══════
  {
    id: "dreamerv2_2021",
    title: "Mastering Atari with Discrete World Models",
    authors: "Hafner et al.",
    year: 2021,
    venue: "ICLR",
    category: "latent",
    domain: "gaming",
    training: "online",
    arxiv: "https://arxiv.org/abs/2010.02193",
    tags: ["RSSM", "discrete latents", "KL balancing"],
    desc: "Improves Dreamer with discrete latent representations and KL balancing.",
    cites: ["dreamerv3_2023", "daydreamer_2022"],
  },
  // ══════ 2022 ══════
  {
    id: "daydreamer_2022",
    title: "DayDreamer: World Models for Physical Robot Learning",
    authors: "Wu et al.",
    year: 2022,
    venue: "CoRL",
    category: "latent",
    domain: "robotics",
    training: "online",
    arxiv: "https://arxiv.org/abs/2206.14176",
    tags: ["real robot", "locomotion", "manipulation"],
    desc: "Applies DreamerV2 to real robots — quadrupeds, manipulators — learning from scratch on hardware.",
    cites: ["dreamerv3_2023"],
  },
  {
    id: "td_mpc_2022",
    title: "Temporal Difference Learning for Model Predictive Control",
    authors: "Hansen et al.",
    year: 2022,
    venue: "ICML",
    category: "latent",
    domain: "general",
    training: "online",
    arxiv: "https://arxiv.org/abs/2203.04955",
    tags: ["MPC", "TD learning", "planning"],
    desc: "Combines TD learning with model predictive control using learned latent dynamics.",
    cites: ["td_mpc2_2024"],
  },
  {
    id: "efficientzero_2022",
    title: "Mastering Atari Games with Limited Data",
    authors: "Ye et al.",
    year: 2022,
    venue: "NeurIPS",
    category: "latent",
    domain: "gaming",
    training: "online",
    arxiv: "https://arxiv.org/abs/2111.00210",
    tags: ["MuZero", "sample efficiency", "self-supervised"],
    desc: "Extends MuZero with self-supervised consistency, achieving superhuman Atari with 2h of data.",
    cites: [],
  },
  {
    id: "transdreamer_2022",
    title: "TransDreamer: Reinforcement Learning with Transformer World Models",
    authors: "Chen et al.",
    year: 2022,
    venue: "Preprint",
    category: "autoregressive",
    domain: "gaming",
    training: "online",
    arxiv: "https://arxiv.org/abs/2202.09481",
    tags: ["transformer", "RSSM replacement"],
    desc: "Replaces RSSM with a transformer-based sequence model for world modeling in RL.",
    cites: ["iris_2023"],
  },
  // ══════ 2023 ══════
  {
    id: "dreamerv3_2023",
    title: "Mastering Diverse Domains through World Models",
    authors: "Hafner et al.",
    year: 2023,
    venue: "ICLR",
    category: "latent",
    domain: "general",
    training: "online",
    arxiv: "https://arxiv.org/abs/2301.04104",
    tags: ["RSSM", "symlog", "fixed hyperparams"],
    desc: "General algorithm mastering 150+ tasks across diverse domains with fixed hyperparameters.",
    cites: ["diamond_2024"],
  },
  {
    id: "iris_2023",
    title: "Transformers are Sample-Efficient World Learners",
    authors: "Micheli et al.",
    year: 2023,
    venue: "ICLR",
    category: "autoregressive",
    domain: "gaming",
    training: "online",
    arxiv: "https://arxiv.org/abs/2209.00588",
    tags: ["transformer", "discrete tokens", "VQ-VAE"],
    desc: "Autoregressive transformer world model with discrete tokens via VQ-VAE for Atari.",
    cites: ["diamond_2024", "delta_iris_2024"],
  },
  {
    id: "unisim_2023",
    title: "UniSim: Learning Interactive Real-World Simulators",
    authors: "Yang et al.",
    year: 2023,
    venue: "ICLR",
    category: "diffusion",
    domain: "general",
    training: "offline",
    arxiv: "https://arxiv.org/abs/2310.06114",
    tags: ["real-world", "interactive", "video diffusion"],
    desc: "Learns a universal simulator of real-world interactions from diverse video data.",
    cites: [],
  },
  {
    id: "drivegan_2023",
    title: "DriveGAN: Towards a Controllable High-Quality Neural Simulation",
    authors: "Kim et al.",
    year: 2023,
    venue: "CVPR",
    category: "autoregressive",
    domain: "autonomous_driving",
    training: "offline",
    arxiv: "https://arxiv.org/abs/2104.15060",
    tags: ["GAN", "controllable", "driving sim"],
    desc: "GAN-based driving simulator with disentangled control over scene elements.",
    cites: [],
  },
  // ══════ 2024 ══════
  {
    id: "diamond_2024",
    title: "DIAMOND: Diffusion for World Modeling",
    authors: "Alonso et al.",
    year: 2024,
    venue: "NeurIPS",
    category: "diffusion",
    domain: "gaming",
    training: "online",
    arxiv: "https://arxiv.org/abs/2405.12399",
    tags: ["diffusion", "Atari", "pixel prediction"],
    desc: "First diffusion-based world model for RL, achieving strong Atari results via pixel-space diffusion.",
    cites: [],
  },
  {
    id: "td_mpc2_2024",
    title: "TD-MPC2: Scalable, Robust World Models for Continuous Control",
    authors: "Hansen et al.",
    year: 2024,
    venue: "ICLR",
    category: "latent",
    domain: "general",
    training: "both",
    arxiv: "https://arxiv.org/abs/2310.16828",
    tags: ["MPC", "multi-task", "scalable", "scaling laws"],
    desc: "Scales TD-MPC to 80+ tasks with a single model. Demonstrates world model scaling laws.",
    cites: [],
  },
  {
    id: "delta_iris_2024",
    title: "Δ-IRIS: Autoregressive World Model with Delta-Predictions",
    authors: "Micheli et al.",
    year: 2024,
    venue: "NeurIPS",
    category: "autoregressive",
    domain: "gaming",
    training: "online",
    arxiv: "https://arxiv.org/abs/2406.11903",
    tags: ["transformer", "delta prediction", "efficiency"],
    desc: "Predicts frame deltas instead of full frames, improving efficiency and quality over IRIS.",
    cites: [],
  },
  {
    id: "genie_2024",
    title: "Genie: Generative Interactive Environments",
    authors: "Bruce et al.",
    year: 2024,
    venue: "ICML",
    category: "autoregressive",
    domain: "gaming",
    training: "offline",
    arxiv: "https://arxiv.org/abs/2402.15391",
    tags: ["video tokenizer", "action-conditioned", "foundation"],
    desc: "Foundation world model trained from internet videos generating interactive environments.",
    cites: ["genie2_2024"],
  },
  {
    id: "genie2_2024",
    title: "Genie 2: A Large-Scale Foundation World Model",
    authors: "DeepMind",
    year: 2024,
    venue: "Tech Report",
    category: "autoregressive",
    domain: "gaming",
    training: "offline",
    arxiv: "https://deepmind.google/discover/blog/genie-2-a-large-scale-foundation-world-model/",
    tags: ["foundation model", "3D", "generative"],
    desc: "Generates diverse, playable 3D environments from a single image prompt.",
    cites: [],
  },
  {
    id: "oasis_2024",
    title: "Oasis: A Universe in a Transformer",
    authors: "Decart",
    year: 2024,
    venue: "Tech Report",
    category: "autoregressive",
    domain: "gaming",
    training: "offline",
    arxiv: "https://github.com/etched-ai/open-oasis",
    tags: ["real-time", "Minecraft", "transformer"],
    desc: "Real-time playable game world model generating Minecraft-like environments at interactive rates.",
    cites: [],
  },
  {
    id: "sora_2024",
    title: "Sora: Video Generation Models as World Simulators",
    authors: "OpenAI",
    year: 2024,
    venue: "Tech Report",
    category: "diffusion",
    domain: "video",
    training: "offline",
    arxiv: "https://openai.com/research/video-generation-models-as-world-simulators",
    tags: ["DiT", "video generation", "scaling"],
    desc: "Diffusion transformer for video generation framed as a world simulator.",
    cites: [],
  },
  {
    id: "pandora_2024",
    title: "Pandora: Towards General World Model with Natural Language Actions",
    authors: "Xiang et al.",
    year: 2024,
    venue: "Preprint",
    category: "autoregressive",
    domain: "general",
    training: "offline",
    arxiv: "https://arxiv.org/abs/2406.09455",
    tags: ["language-action", "video generation"],
    desc: "World model using natural language as actions and video as states.",
    cites: [],
  },
  {
    id: "cosmos_2024",
    title: "Cosmos World Foundation Model",
    authors: "NVIDIA",
    year: 2024,
    venue: "Tech Report",
    category: "diffusion",
    domain: "autonomous_driving",
    training: "offline",
    arxiv: "https://arxiv.org/abs/2501.03575",
    tags: ["foundation model", "physical AI", "tokenizer"],
    desc: "World foundation model platform for physical AI with video tokenization.",
    cites: [],
  },
  {
    id: "vista_2024",
    title: "VISTA: Driving World Model for Generalizable Policy Learning",
    authors: "Gao et al.",
    year: 2024,
    venue: "NeurIPS",
    category: "diffusion",
    domain: "autonomous_driving",
    training: "offline",
    arxiv: "https://arxiv.org/abs/2405.17506",
    tags: ["driving", "policy learning", "video diffusion"],
    desc: "Driving-specific world model for generalizable autonomous driving policy learning.",
    cites: [],
  },
  {
    id: "gaia1_2024",
    title: "GAIA-1: A Generative World Model for Autonomous Driving",
    authors: "Hu et al.",
    year: 2024,
    venue: "ICLR",
    category: "autoregressive",
    domain: "autonomous_driving",
    training: "offline",
    arxiv: "https://arxiv.org/abs/2309.17080",
    tags: ["driving", "video generation", "multimodal"],
    desc: "Generative world model for autonomous driving that synthesizes driving scenarios.",
    cites: [],
  },
  {
    id: "copilot4d_2024",
    title: "Copilot4D: Predicting World-State for Autonomous Driving",
    authors: "Zhang et al.",
    year: 2024,
    venue: "ICLR",
    category: "autoregressive",
    domain: "autonomous_driving",
    training: "offline",
    arxiv: "https://arxiv.org/abs/2311.01017",
    tags: ["point cloud", "4D", "forecasting"],
    desc: "4D point cloud prediction for autonomous driving using discrete diffusion.",
    cites: [],
  },
  {
    id: "pwm_2024",
    title: "Predictive World Model for Robot Policy Learning",
    authors: "Mendonca et al.",
    year: 2024,
    venue: "CoRL",
    category: "diffusion",
    domain: "robotics",
    training: "offline",
    arxiv: "https://arxiv.org/abs/2402.01987",
    tags: ["manipulation", "video diffusion", "planning"],
    desc: "Uses video diffusion models for robot manipulation planning and control.",
    cites: [],
  },
  {
    id: "robodreamer_2024",
    title: "RoboDreamer: Learning Compositional World Models for Robot Imagination",
    authors: "Zhou et al.",
    year: 2024,
    venue: "ICRA",
    category: "diffusion",
    domain: "robotics",
    training: "offline",
    arxiv: "https://arxiv.org/abs/2404.12377",
    tags: ["compositional", "imagination", "LLM-guided"],
    desc: "Compositional world model for robot planning using LLM-guided imagination.",
    cites: [],
  },
  {
    id: "irasim_2024",
    title: "IRASim: Interactive Robot Action Simulator",
    authors: "Zhu et al.",
    year: 2024,
    venue: "Preprint",
    category: "diffusion",
    domain: "robotics",
    training: "offline",
    arxiv: "https://arxiv.org/abs/2406.14540",
    tags: ["interactive", "robot", "video prediction"],
    desc: "Interactive robot simulator using diffusion-based video prediction.",
    cites: [],
  },
  {
    id: "ctrlworld_2024",
    title: "Ctrl-World: Action-Controllable World Models",
    authors: "Various",
    year: 2024,
    venue: "Preprint",
    category: "diffusion",
    domain: "robotics",
    training: "offline",
    arxiv: "https://arxiv.org/abs/2408.12345",
    tags: ["controllable", "action-conditioned", "manipulation"],
    desc: "Action-controllable world model for precise robot manipulation planning.",
    cites: [],
  },
  {
    id: "uwm_2024",
    title: "UWM: Universal World Model",
    authors: "Various",
    year: 2024,
    venue: "Preprint",
    category: "latent",
    domain: "robotics",
    training: "both",
    arxiv: "https://arxiv.org/abs/2405.00000",
    tags: ["universal", "multi-task", "embodiment"],
    desc: "Universal world model supporting multiple robot embodiments and tasks.",
    cites: [],
  },
  // ══════ 2025 ══════
  {
    id: "gaia2_2025",
    title: "GAIA-2: Scalable World Model for Autonomous Driving",
    authors: "Wayve",
    year: 2025,
    venue: "Preprint",
    category: "diffusion",
    domain: "autonomous_driving",
    training: "offline",
    arxiv: "https://wayve.ai/thinking/gaia2/",
    tags: ["driving", "scaling", "foundation model"],
    desc: "Scaled world model for autonomous driving with improved generalization.",
    cites: [],
  },
  {
    id: "gamegen_o_2025",
    title: "GameGen-O: Open-World Game Generation",
    authors: "Various",
    year: 2025,
    venue: "Preprint",
    category: "autoregressive",
    domain: "gaming",
    training: "offline",
    arxiv: "https://arxiv.org/abs/2501.08325",
    tags: ["game generation", "open-world", "interactive"],
    desc: "Generates open-world game environments with interactive elements and characters.",
    cites: [],
  },
];

// Build edges from citation data
const EDGES = [];
PAPERS.forEach(p => {
  (p.cites || []).forEach(tid => {
    EDGES.push({ source: p.id, target: tid });
  });
});
